/*
Saviynt API

API for managing jobs in Saviynt.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package job_control

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckJobStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckJobStatusResponse{}

// CheckJobStatusResponse Response for the check job status operation
type CheckJobStatusResponse struct {
	// Message indicating the result of the operation
	Msg string `json:"msg"`
	// Error code if the operation failed
	ErrorCode string `json:"errorCode"`
}

type _CheckJobStatusResponse CheckJobStatusResponse

// NewCheckJobStatusResponse instantiates a new CheckJobStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckJobStatusResponse(msg string, errorCode string) *CheckJobStatusResponse {
	this := CheckJobStatusResponse{}
	this.Msg = msg
	this.ErrorCode = errorCode
	return &this
}

// NewCheckJobStatusResponseWithDefaults instantiates a new CheckJobStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckJobStatusResponseWithDefaults() *CheckJobStatusResponse {
	this := CheckJobStatusResponse{}
	return &this
}

// GetMsg returns the Msg field value
func (o *CheckJobStatusResponse) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *CheckJobStatusResponse) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *CheckJobStatusResponse) SetMsg(v string) {
	o.Msg = v
}

// GetErrorCode returns the ErrorCode field value
func (o *CheckJobStatusResponse) GetErrorCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value
// and a boolean to check if the value has been set.
func (o *CheckJobStatusResponse) GetErrorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorCode, true
}

// SetErrorCode sets field value
func (o *CheckJobStatusResponse) SetErrorCode(v string) {
	o.ErrorCode = v
}

func (o CheckJobStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckJobStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["msg"] = o.Msg
	toSerialize["errorCode"] = o.ErrorCode
	return toSerialize, nil
}

func (o *CheckJobStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"msg",
		"errorCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckJobStatusResponse := _CheckJobStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckJobStatusResponse)

	if err != nil {
		return err
	}

	*o = CheckJobStatusResponse(varCheckJobStatusResponse)

	return err
}

type NullableCheckJobStatusResponse struct {
	value *CheckJobStatusResponse
	isSet bool
}

func (v NullableCheckJobStatusResponse) Get() *CheckJobStatusResponse {
	return v.value
}

func (v *NullableCheckJobStatusResponse) Set(val *CheckJobStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckJobStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckJobStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckJobStatusResponse(val *CheckJobStatusResponse) *NullableCheckJobStatusResponse {
	return &NullableCheckJobStatusResponse{value: val, isSet: true}
}

func (v NullableCheckJobStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckJobStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


