/*
Saviynt API

API for managing jobs in Saviynt.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package job_control

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplicationDataImportJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationDataImportJob{}

// ApplicationDataImportJob struct for ApplicationDataImportJob
type ApplicationDataImportJob struct {
	BaseTrigger
	ValueMap *ApplicationDataImportJobAllOfValueMap `json:"valueMap,omitempty"`
}

type _ApplicationDataImportJob ApplicationDataImportJob

// NewApplicationDataImportJob instantiates a new ApplicationDataImportJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationDataImportJob(triggername string, jobname string, jobgroup string, cronexpression string) *ApplicationDataImportJob {
	this := ApplicationDataImportJob{}
	this.Triggername = triggername
	this.Jobname = jobname
	this.Jobgroup = jobgroup
	this.Cronexpression = cronexpression
	return &this
}

// NewApplicationDataImportJobWithDefaults instantiates a new ApplicationDataImportJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationDataImportJobWithDefaults() *ApplicationDataImportJob {
	this := ApplicationDataImportJob{}
	return &this
}

// GetValueMap returns the ValueMap field value if set, zero value otherwise.
func (o *ApplicationDataImportJob) GetValueMap() ApplicationDataImportJobAllOfValueMap {
	if o == nil || IsNil(o.ValueMap) {
		var ret ApplicationDataImportJobAllOfValueMap
		return ret
	}
	return *o.ValueMap
}

// GetValueMapOk returns a tuple with the ValueMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationDataImportJob) GetValueMapOk() (*ApplicationDataImportJobAllOfValueMap, bool) {
	if o == nil || IsNil(o.ValueMap) {
		return nil, false
	}
	return o.ValueMap, true
}

// HasValueMap returns a boolean if a field has been set.
func (o *ApplicationDataImportJob) HasValueMap() bool {
	if o != nil && !IsNil(o.ValueMap) {
		return true
	}

	return false
}

// SetValueMap gets a reference to the given ApplicationDataImportJobAllOfValueMap and assigns it to the ValueMap field.
func (o *ApplicationDataImportJob) SetValueMap(v ApplicationDataImportJobAllOfValueMap) {
	o.ValueMap = &v
}

func (o ApplicationDataImportJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationDataImportJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseTrigger, errBaseTrigger := json.Marshal(o.BaseTrigger)
	if errBaseTrigger != nil {
		return map[string]interface{}{}, errBaseTrigger
	}
	errBaseTrigger = json.Unmarshal([]byte(serializedBaseTrigger), &toSerialize)
	if errBaseTrigger != nil {
		return map[string]interface{}{}, errBaseTrigger
	}
	if !IsNil(o.ValueMap) {
		toSerialize["valueMap"] = o.ValueMap
	}
	return toSerialize, nil
}

func (o *ApplicationDataImportJob) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"triggername",
		"jobname",
		"jobgroup",
		"cronexpression",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationDataImportJob := _ApplicationDataImportJob{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationDataImportJob)

	if err != nil {
		return err
	}

	*o = ApplicationDataImportJob(varApplicationDataImportJob)

	return err
}

type NullableApplicationDataImportJob struct {
	value *ApplicationDataImportJob
	isSet bool
}

func (v NullableApplicationDataImportJob) Get() *ApplicationDataImportJob {
	return v.value
}

func (v *NullableApplicationDataImportJob) Set(val *ApplicationDataImportJob) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationDataImportJob) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationDataImportJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationDataImportJob(val *ApplicationDataImportJob) *NullableApplicationDataImportJob {
	return &NullableApplicationDataImportJob{value: val, isSet: true}
}

func (v NullableApplicationDataImportJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationDataImportJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


