/*
Saviynt API

API for managing jobs in Saviynt.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package job_control

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SchemaUserJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaUserJob{}

// SchemaUserJob struct for SchemaUserJob
type SchemaUserJob struct {
	BaseJobTrigger
	ValueMap *SchemaUserJobAllOfValueMap `json:"valueMap,omitempty"`
}

type _SchemaUserJob SchemaUserJob

// NewSchemaUserJob instantiates a new SchemaUserJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaUserJob(name string, jobName string, jobGroup string, group string, cronExp string) *SchemaUserJob {
	this := SchemaUserJob{}
	this.Name = name
	this.JobName = jobName
	this.JobGroup = jobGroup
	this.Group = group
	this.CronExp = cronExp
	return &this
}

// NewSchemaUserJobWithDefaults instantiates a new SchemaUserJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaUserJobWithDefaults() *SchemaUserJob {
	this := SchemaUserJob{}
	return &this
}

// GetValueMap returns the ValueMap field value if set, zero value otherwise.
func (o *SchemaUserJob) GetValueMap() SchemaUserJobAllOfValueMap {
	if o == nil || IsNil(o.ValueMap) {
		var ret SchemaUserJobAllOfValueMap
		return ret
	}
	return *o.ValueMap
}

// GetValueMapOk returns a tuple with the ValueMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaUserJob) GetValueMapOk() (*SchemaUserJobAllOfValueMap, bool) {
	if o == nil || IsNil(o.ValueMap) {
		return nil, false
	}
	return o.ValueMap, true
}

// HasValueMap returns a boolean if a field has been set.
func (o *SchemaUserJob) HasValueMap() bool {
	if o != nil && !IsNil(o.ValueMap) {
		return true
	}

	return false
}

// SetValueMap gets a reference to the given SchemaUserJobAllOfValueMap and assigns it to the ValueMap field.
func (o *SchemaUserJob) SetValueMap(v SchemaUserJobAllOfValueMap) {
	o.ValueMap = &v
}

func (o SchemaUserJob) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaUserJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseJobTrigger, errBaseJobTrigger := json.Marshal(o.BaseJobTrigger)
	if errBaseJobTrigger != nil {
		return map[string]interface{}{}, errBaseJobTrigger
	}
	errBaseJobTrigger = json.Unmarshal([]byte(serializedBaseJobTrigger), &toSerialize)
	if errBaseJobTrigger != nil {
		return map[string]interface{}{}, errBaseJobTrigger
	}
	if !IsNil(o.ValueMap) {
		toSerialize["valueMap"] = o.ValueMap
	}
	return toSerialize, nil
}

func (o *SchemaUserJob) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"jobName",
		"jobGroup",
		"group",
		"cronExp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchemaUserJob := _SchemaUserJob{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSchemaUserJob)

	if err != nil {
		return err
	}

	*o = SchemaUserJob(varSchemaUserJob)

	return err
}

type NullableSchemaUserJob struct {
	value *SchemaUserJob
	isSet bool
}

func (v NullableSchemaUserJob) Get() *SchemaUserJob {
	return v.value
}

func (v *NullableSchemaUserJob) Set(val *SchemaUserJob) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaUserJob) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaUserJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaUserJob(val *SchemaUserJob) *NullableSchemaUserJob {
	return &NullableSchemaUserJob{value: val, isSet: true}
}

func (v NullableSchemaUserJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaUserJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
