/*
Saviynt API

API for managing jobs in Saviynt.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package job_control

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RunJobTriggerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunJobTriggerRequest{}

// RunJobTriggerRequest Request body for running a job trigger
type RunJobTriggerRequest struct {
	// Name of the job to run
	Jobname string `json:"jobname"`
	// Name of the trigger to run
	Triggername string `json:"triggername"`
	// Group of the job to run
	Jobgroup string `json:"jobgroup"`
}

type _RunJobTriggerRequest RunJobTriggerRequest

// NewRunJobTriggerRequest instantiates a new RunJobTriggerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunJobTriggerRequest(jobname string, triggername string, jobgroup string) *RunJobTriggerRequest {
	this := RunJobTriggerRequest{}
	this.Jobname = jobname
	this.Triggername = triggername
	this.Jobgroup = jobgroup
	return &this
}

// NewRunJobTriggerRequestWithDefaults instantiates a new RunJobTriggerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunJobTriggerRequestWithDefaults() *RunJobTriggerRequest {
	this := RunJobTriggerRequest{}
	return &this
}

// GetJobname returns the Jobname field value
func (o *RunJobTriggerRequest) GetJobname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Jobname
}

// GetJobnameOk returns a tuple with the Jobname field value
// and a boolean to check if the value has been set.
func (o *RunJobTriggerRequest) GetJobnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jobname, true
}

// SetJobname sets field value
func (o *RunJobTriggerRequest) SetJobname(v string) {
	o.Jobname = v
}

// GetTriggername returns the Triggername field value
func (o *RunJobTriggerRequest) GetTriggername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Triggername
}

// GetTriggernameOk returns a tuple with the Triggername field value
// and a boolean to check if the value has been set.
func (o *RunJobTriggerRequest) GetTriggernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Triggername, true
}

// SetTriggername sets field value
func (o *RunJobTriggerRequest) SetTriggername(v string) {
	o.Triggername = v
}

// GetJobgroup returns the Jobgroup field value
func (o *RunJobTriggerRequest) GetJobgroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Jobgroup
}

// GetJobgroupOk returns a tuple with the Jobgroup field value
// and a boolean to check if the value has been set.
func (o *RunJobTriggerRequest) GetJobgroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jobgroup, true
}

// SetJobgroup sets field value
func (o *RunJobTriggerRequest) SetJobgroup(v string) {
	o.Jobgroup = v
}

func (o RunJobTriggerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunJobTriggerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobname"] = o.Jobname
	toSerialize["triggername"] = o.Triggername
	toSerialize["jobgroup"] = o.Jobgroup
	return toSerialize, nil
}

func (o *RunJobTriggerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobname",
		"triggername",
		"jobgroup",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunJobTriggerRequest := _RunJobTriggerRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRunJobTriggerRequest)

	if err != nil {
		return err
	}

	*o = RunJobTriggerRequest(varRunJobTriggerRequest)

	return err
}

type NullableRunJobTriggerRequest struct {
	value *RunJobTriggerRequest
	isSet bool
}

func (v NullableRunJobTriggerRequest) Get() *RunJobTriggerRequest {
	return v.value
}

func (v *NullableRunJobTriggerRequest) Set(val *RunJobTriggerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRunJobTriggerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRunJobTriggerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunJobTriggerRequest(val *RunJobTriggerRequest) *NullableRunJobTriggerRequest {
	return &NullableRunJobTriggerRequest{value: val, isSet: true}
}

func (v NullableRunJobTriggerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunJobTriggerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
