/*
Connection Management API

Use this API to create a connection in Saviynt Identity Cloud.  The Authorization header must have \"Bearer {token}\".  **Mandatory Parameters:** - **connectionname**: Specify the name to identify the connection. - **connectiontype**: Specify a connection type. For example, if your target application is Active Directory, specify the connection type as \"AD\".  **Optional Parameters:** - **description**: Provide a description for the connection. - **defaultsavroles**: Specify the SAV role(s) required for managing this connection along with its associated security systems, endpoints, accounts, and entitlements. - **emailTemplate**: Specify the email template applicable for notifications. - **sslCertificate**: Specify the SSL certificate(s) to secure the connection between EIC and the target application. - **vaultConfiguration**: Specify the path of the vault to obtain secret data (suffix the connector name to make it unique). - **saveinvault**: Set to true to save the encrypted attribute in the configured vault.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connections

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SFTPConnector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SFTPConnector{}

// SFTPConnector struct for SFTPConnector
type SFTPConnector struct {
	BaseConnector
	// SFTP server hostname or IP address
	HOST_NAME string `json:"HOST_NAME"`
	// SFTP server port number
	PORT_NUMBER string `json:"PORT_NUMBER"`
	// Username for SFTP authentication
	USERNAME string `json:"USERNAME"`
	// Type of authentication (password, key, etc.)
	AUTH_CREDENTIAL_TYPE string `json:"AUTH_CREDENTIAL_TYPE"`
	// Authentication credential (password or private key path)
	AUTH_CREDENTIAL_VALUE string `json:"AUTH_CREDENTIAL_VALUE"`
	// Passphrase for encrypted private key
	PASSPHRASE *string `json:"PASSPHRASE,omitempty"`
	// Files to download from SFTP server
	FILES_TO_GET *string `json:"FILES_TO_GET,omitempty"`
	// Files to upload to SFTP server
	FILES_TO_PUT *string `json:"FILES_TO_PUT,omitempty"`
	// PAM configuration for SFTP connection
	PAM_CONFIG *string `json:"PAM_CONFIG,omitempty"`
}

type _SFTPConnector SFTPConnector

// NewSFTPConnector instantiates a new SFTPConnector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSFTPConnector(hOSTNAME string, pORTNUMBER string, uSERNAME string, aUTHCREDENTIALTYPE string, aUTHCREDENTIALVALUE string, connectionName string, connectiontype string) *SFTPConnector {
	this := SFTPConnector{}
	this.ConnectionName = connectionName
	this.Connectiontype = connectiontype
	this.HOST_NAME = hOSTNAME
	this.PORT_NUMBER = pORTNUMBER
	this.USERNAME = uSERNAME
	this.AUTH_CREDENTIAL_TYPE = aUTHCREDENTIALTYPE
	this.AUTH_CREDENTIAL_VALUE = aUTHCREDENTIALVALUE
	return &this
}

// NewSFTPConnectorWithDefaults instantiates a new SFTPConnector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSFTPConnectorWithDefaults() *SFTPConnector {
	this := SFTPConnector{}
	return &this
}

// GetHOST_NAME returns the HOST_NAME field value
func (o *SFTPConnector) GetHOST_NAME() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HOST_NAME
}

// GetHOST_NAMEOk returns a tuple with the HOST_NAME field value
// and a boolean to check if the value has been set.
func (o *SFTPConnector) GetHOST_NAMEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HOST_NAME, true
}

// SetHOST_NAME sets field value
func (o *SFTPConnector) SetHOST_NAME(v string) {
	o.HOST_NAME = v
}

// GetPORT_NUMBER returns the PORT_NUMBER field value
func (o *SFTPConnector) GetPORT_NUMBER() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PORT_NUMBER
}

// GetPORT_NUMBEROk returns a tuple with the PORT_NUMBER field value
// and a boolean to check if the value has been set.
func (o *SFTPConnector) GetPORT_NUMBEROk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PORT_NUMBER, true
}

// SetPORT_NUMBER sets field value
func (o *SFTPConnector) SetPORT_NUMBER(v string) {
	o.PORT_NUMBER = v
}

// GetUSERNAME returns the USERNAME field value
func (o *SFTPConnector) GetUSERNAME() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.USERNAME
}

// GetUSERNAMEOk returns a tuple with the USERNAME field value
// and a boolean to check if the value has been set.
func (o *SFTPConnector) GetUSERNAMEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.USERNAME, true
}

// SetUSERNAME sets field value
func (o *SFTPConnector) SetUSERNAME(v string) {
	o.USERNAME = v
}

// GetAUTH_CREDENTIAL_TYPE returns the AUTH_CREDENTIAL_TYPE field value
func (o *SFTPConnector) GetAUTH_CREDENTIAL_TYPE() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AUTH_CREDENTIAL_TYPE
}

// GetAUTH_CREDENTIAL_TYPEOk returns a tuple with the AUTH_CREDENTIAL_TYPE field value
// and a boolean to check if the value has been set.
func (o *SFTPConnector) GetAUTH_CREDENTIAL_TYPEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AUTH_CREDENTIAL_TYPE, true
}

// SetAUTH_CREDENTIAL_TYPE sets field value
func (o *SFTPConnector) SetAUTH_CREDENTIAL_TYPE(v string) {
	o.AUTH_CREDENTIAL_TYPE = v
}

// GetAUTH_CREDENTIAL_VALUE returns the AUTH_CREDENTIAL_VALUE field value
func (o *SFTPConnector) GetAUTH_CREDENTIAL_VALUE() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AUTH_CREDENTIAL_VALUE
}

// GetAUTH_CREDENTIAL_VALUEOk returns a tuple with the AUTH_CREDENTIAL_VALUE field value
// and a boolean to check if the value has been set.
func (o *SFTPConnector) GetAUTH_CREDENTIAL_VALUEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AUTH_CREDENTIAL_VALUE, true
}

// SetAUTH_CREDENTIAL_VALUE sets field value
func (o *SFTPConnector) SetAUTH_CREDENTIAL_VALUE(v string) {
	o.AUTH_CREDENTIAL_VALUE = v
}

// GetPASSPHRASE returns the PASSPHRASE field value if set, zero value otherwise.
func (o *SFTPConnector) GetPASSPHRASE() string {
	if o == nil || IsNil(o.PASSPHRASE) {
		var ret string
		return ret
	}
	return *o.PASSPHRASE
}

// GetPASSPHRASEOk returns a tuple with the PASSPHRASE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnector) GetPASSPHRASEOk() (*string, bool) {
	if o == nil || IsNil(o.PASSPHRASE) {
		return nil, false
	}
	return o.PASSPHRASE, true
}

// HasPASSPHRASE returns a boolean if a field has been set.
func (o *SFTPConnector) HasPASSPHRASE() bool {
	if o != nil && !IsNil(o.PASSPHRASE) {
		return true
	}

	return false
}

// SetPASSPHRASE gets a reference to the given string and assigns it to the PASSPHRASE field.
func (o *SFTPConnector) SetPASSPHRASE(v string) {
	o.PASSPHRASE = &v
}

// GetFILES_TO_GET returns the FILES_TO_GET field value if set, zero value otherwise.
func (o *SFTPConnector) GetFILES_TO_GET() string {
	if o == nil || IsNil(o.FILES_TO_GET) {
		var ret string
		return ret
	}
	return *o.FILES_TO_GET
}

// GetFILES_TO_GETOk returns a tuple with the FILES_TO_GET field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnector) GetFILES_TO_GETOk() (*string, bool) {
	if o == nil || IsNil(o.FILES_TO_GET) {
		return nil, false
	}
	return o.FILES_TO_GET, true
}

// HasFILES_TO_GET returns a boolean if a field has been set.
func (o *SFTPConnector) HasFILES_TO_GET() bool {
	if o != nil && !IsNil(o.FILES_TO_GET) {
		return true
	}

	return false
}

// SetFILES_TO_GET gets a reference to the given string and assigns it to the FILES_TO_GET field.
func (o *SFTPConnector) SetFILES_TO_GET(v string) {
	o.FILES_TO_GET = &v
}

// GetFILES_TO_PUT returns the FILES_TO_PUT field value if set, zero value otherwise.
func (o *SFTPConnector) GetFILES_TO_PUT() string {
	if o == nil || IsNil(o.FILES_TO_PUT) {
		var ret string
		return ret
	}
	return *o.FILES_TO_PUT
}

// GetFILES_TO_PUTOk returns a tuple with the FILES_TO_PUT field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnector) GetFILES_TO_PUTOk() (*string, bool) {
	if o == nil || IsNil(o.FILES_TO_PUT) {
		return nil, false
	}
	return o.FILES_TO_PUT, true
}

// HasFILES_TO_PUT returns a boolean if a field has been set.
func (o *SFTPConnector) HasFILES_TO_PUT() bool {
	if o != nil && !IsNil(o.FILES_TO_PUT) {
		return true
	}

	return false
}

// SetFILES_TO_PUT gets a reference to the given string and assigns it to the FILES_TO_PUT field.
func (o *SFTPConnector) SetFILES_TO_PUT(v string) {
	o.FILES_TO_PUT = &v
}

// GetPAM_CONFIG returns the PAM_CONFIG field value if set, zero value otherwise.
func (o *SFTPConnector) GetPAM_CONFIG() string {
	if o == nil || IsNil(o.PAM_CONFIG) {
		var ret string
		return ret
	}
	return *o.PAM_CONFIG
}

// GetPAM_CONFIGOk returns a tuple with the PAM_CONFIG field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnector) GetPAM_CONFIGOk() (*string, bool) {
	if o == nil || IsNil(o.PAM_CONFIG) {
		return nil, false
	}
	return o.PAM_CONFIG, true
}

// HasPAM_CONFIG returns a boolean if a field has been set.
func (o *SFTPConnector) HasPAM_CONFIG() bool {
	if o != nil && !IsNil(o.PAM_CONFIG) {
		return true
	}

	return false
}

// SetPAM_CONFIG gets a reference to the given string and assigns it to the PAM_CONFIG field.
func (o *SFTPConnector) SetPAM_CONFIG(v string) {
	o.PAM_CONFIG = &v
}

func (o SFTPConnector) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SFTPConnector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseConnector, errBaseConnector := json.Marshal(o.BaseConnector)
	if errBaseConnector != nil {
		return map[string]interface{}{}, errBaseConnector
	}
	errBaseConnector = json.Unmarshal([]byte(serializedBaseConnector), &toSerialize)
	if errBaseConnector != nil {
		return map[string]interface{}{}, errBaseConnector
	}
	toSerialize["HOST_NAME"] = o.HOST_NAME
	toSerialize["PORT_NUMBER"] = o.PORT_NUMBER
	toSerialize["USERNAME"] = o.USERNAME
	toSerialize["AUTH_CREDENTIAL_TYPE"] = o.AUTH_CREDENTIAL_TYPE
	toSerialize["AUTH_CREDENTIAL_VALUE"] = o.AUTH_CREDENTIAL_VALUE
	if !IsNil(o.PASSPHRASE) {
		toSerialize["PASSPHRASE"] = o.PASSPHRASE
	}
	if !IsNil(o.FILES_TO_GET) {
		toSerialize["FILES_TO_GET"] = o.FILES_TO_GET
	}
	if !IsNil(o.FILES_TO_PUT) {
		toSerialize["FILES_TO_PUT"] = o.FILES_TO_PUT
	}
	if !IsNil(o.PAM_CONFIG) {
		toSerialize["PAM_CONFIG"] = o.PAM_CONFIG
	}
	return toSerialize, nil
}

func (o *SFTPConnector) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"HOST_NAME",
		"PORT_NUMBER",
		"USERNAME",
		"AUTH_CREDENTIAL_TYPE",
		"AUTH_CREDENTIAL_VALUE",
		"connectionName",
		"connectiontype",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSFTPConnector := _SFTPConnector{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSFTPConnector)

	if err != nil {
		return err
	}

	*o = SFTPConnector(varSFTPConnector)

	return err
}

type NullableSFTPConnector struct {
	value *SFTPConnector
	isSet bool
}

func (v NullableSFTPConnector) Get() *SFTPConnector {
	return v.value
}

func (v *NullableSFTPConnector) Set(val *SFTPConnector) {
	v.value = val
	v.isSet = true
}

func (v NullableSFTPConnector) IsSet() bool {
	return v.isSet
}

func (v *NullableSFTPConnector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSFTPConnector(val *SFTPConnector) *NullableSFTPConnector {
	return &NullableSFTPConnector{value: val, isSet: true}
}

func (v NullableSFTPConnector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSFTPConnector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
