/*
Connection Management API

Use this API to create a connection in Saviynt Identity Cloud.  The Authorization header must have \"Bearer {token}\".  **Mandatory Parameters:** - **connectionname**: Specify the name to identify the connection. - **connectiontype**: Specify a connection type. For example, if your target application is Active Directory, specify the connection type as \"AD\".  **Optional Parameters:** - **description**: Provide a description for the connection. - **defaultsavroles**: Specify the SAV role(s) required for managing this connection along with its associated security systems, endpoints, accounts, and entitlements. - **emailTemplate**: Specify the email template applicable for notifications. - **sslCertificate**: Specify the SSL certificate(s) to secure the connection between EIC and the target application. - **vaultConfiguration**: Specify the path of the vault to obtain secret data (suffix the connector name to make it unique). - **saveinvault**: Set to true to save the encrypted attribute in the configured vault.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connections

import (
	"encoding/json"
)

// checks if the SFTPConnectionAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SFTPConnectionAttributes{}

// SFTPConnectionAttributes struct for SFTPConnectionAttributes
type SFTPConnectionAttributes struct {
	HOST_NAME                *string                  `json:"HOST_NAME,omitempty"`
	PORT_NUMBER              *string                  `json:"PORT_NUMBER,omitempty"`
	USERNAME                 *string                  `json:"USERNAME,omitempty"`
	AUTH_CREDENTIAL_TYPE     *string                  `json:"AUTH_CREDENTIAL_TYPE,omitempty"`
	AUTH_CREDENTIAL_VALUE    *string                  `json:"AUTH_CREDENTIAL_VALUE,omitempty"`
	PASSPHRASE               *string                  `json:"PASSPHRASE,omitempty"`
	FILES_TO_GET             *string                  `json:"FILES_TO_GET,omitempty"`
	FILES_TO_PUT             *string                  `json:"FILES_TO_PUT,omitempty"`
	PAM_CONFIG               *string                  `json:"PAM_CONFIG,omitempty"`
	ConnectionType           *string                  `json:"connectionType,omitempty"`
	IsTimeoutSupported       *bool                    `json:"isTimeoutSupported,omitempty"`
	IsTimeoutConfigValidated *bool                    `json:"isTimeoutConfigValidated,omitempty"`
	ConnectionTimeoutConfig  *ConnectionTimeoutConfig `json:"connectionTimeoutConfig,omitempty"`
}

// NewSFTPConnectionAttributes instantiates a new SFTPConnectionAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSFTPConnectionAttributes() *SFTPConnectionAttributes {
	this := SFTPConnectionAttributes{}
	return &this
}

// NewSFTPConnectionAttributesWithDefaults instantiates a new SFTPConnectionAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSFTPConnectionAttributesWithDefaults() *SFTPConnectionAttributes {
	this := SFTPConnectionAttributes{}
	return &this
}

// GetHOST_NAME returns the HOST_NAME field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetHOST_NAME() string {
	if o == nil || IsNil(o.HOST_NAME) {
		var ret string
		return ret
	}
	return *o.HOST_NAME
}

// GetHOST_NAMEOk returns a tuple with the HOST_NAME field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetHOST_NAMEOk() (*string, bool) {
	if o == nil || IsNil(o.HOST_NAME) {
		return nil, false
	}
	return o.HOST_NAME, true
}

// HasHOST_NAME returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasHOST_NAME() bool {
	if o != nil && !IsNil(o.HOST_NAME) {
		return true
	}

	return false
}

// SetHOST_NAME gets a reference to the given string and assigns it to the HOST_NAME field.
func (o *SFTPConnectionAttributes) SetHOST_NAME(v string) {
	o.HOST_NAME = &v
}

// GetPORT_NUMBER returns the PORT_NUMBER field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetPORT_NUMBER() string {
	if o == nil || IsNil(o.PORT_NUMBER) {
		var ret string
		return ret
	}
	return *o.PORT_NUMBER
}

// GetPORT_NUMBEROk returns a tuple with the PORT_NUMBER field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetPORT_NUMBEROk() (*string, bool) {
	if o == nil || IsNil(o.PORT_NUMBER) {
		return nil, false
	}
	return o.PORT_NUMBER, true
}

// HasPORT_NUMBER returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasPORT_NUMBER() bool {
	if o != nil && !IsNil(o.PORT_NUMBER) {
		return true
	}

	return false
}

// SetPORT_NUMBER gets a reference to the given string and assigns it to the PORT_NUMBER field.
func (o *SFTPConnectionAttributes) SetPORT_NUMBER(v string) {
	o.PORT_NUMBER = &v
}

// GetUSERNAME returns the USERNAME field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetUSERNAME() string {
	if o == nil || IsNil(o.USERNAME) {
		var ret string
		return ret
	}
	return *o.USERNAME
}

// GetUSERNAMEOk returns a tuple with the USERNAME field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetUSERNAMEOk() (*string, bool) {
	if o == nil || IsNil(o.USERNAME) {
		return nil, false
	}
	return o.USERNAME, true
}

// HasUSERNAME returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasUSERNAME() bool {
	if o != nil && !IsNil(o.USERNAME) {
		return true
	}

	return false
}

// SetUSERNAME gets a reference to the given string and assigns it to the USERNAME field.
func (o *SFTPConnectionAttributes) SetUSERNAME(v string) {
	o.USERNAME = &v
}

// GetAUTH_CREDENTIAL_TYPE returns the AUTH_CREDENTIAL_TYPE field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetAUTH_CREDENTIAL_TYPE() string {
	if o == nil || IsNil(o.AUTH_CREDENTIAL_TYPE) {
		var ret string
		return ret
	}
	return *o.AUTH_CREDENTIAL_TYPE
}

// GetAUTH_CREDENTIAL_TYPEOk returns a tuple with the AUTH_CREDENTIAL_TYPE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetAUTH_CREDENTIAL_TYPEOk() (*string, bool) {
	if o == nil || IsNil(o.AUTH_CREDENTIAL_TYPE) {
		return nil, false
	}
	return o.AUTH_CREDENTIAL_TYPE, true
}

// HasAUTH_CREDENTIAL_TYPE returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasAUTH_CREDENTIAL_TYPE() bool {
	if o != nil && !IsNil(o.AUTH_CREDENTIAL_TYPE) {
		return true
	}

	return false
}

// SetAUTH_CREDENTIAL_TYPE gets a reference to the given string and assigns it to the AUTH_CREDENTIAL_TYPE field.
func (o *SFTPConnectionAttributes) SetAUTH_CREDENTIAL_TYPE(v string) {
	o.AUTH_CREDENTIAL_TYPE = &v
}

// GetAUTH_CREDENTIAL_VALUE returns the AUTH_CREDENTIAL_VALUE field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetAUTH_CREDENTIAL_VALUE() string {
	if o == nil || IsNil(o.AUTH_CREDENTIAL_VALUE) {
		var ret string
		return ret
	}
	return *o.AUTH_CREDENTIAL_VALUE
}

// GetAUTH_CREDENTIAL_VALUEOk returns a tuple with the AUTH_CREDENTIAL_VALUE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetAUTH_CREDENTIAL_VALUEOk() (*string, bool) {
	if o == nil || IsNil(o.AUTH_CREDENTIAL_VALUE) {
		return nil, false
	}
	return o.AUTH_CREDENTIAL_VALUE, true
}

// HasAUTH_CREDENTIAL_VALUE returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasAUTH_CREDENTIAL_VALUE() bool {
	if o != nil && !IsNil(o.AUTH_CREDENTIAL_VALUE) {
		return true
	}

	return false
}

// SetAUTH_CREDENTIAL_VALUE gets a reference to the given string and assigns it to the AUTH_CREDENTIAL_VALUE field.
func (o *SFTPConnectionAttributes) SetAUTH_CREDENTIAL_VALUE(v string) {
	o.AUTH_CREDENTIAL_VALUE = &v
}

// GetPASSPHRASE returns the PASSPHRASE field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetPASSPHRASE() string {
	if o == nil || IsNil(o.PASSPHRASE) {
		var ret string
		return ret
	}
	return *o.PASSPHRASE
}

// GetPASSPHRASEOk returns a tuple with the PASSPHRASE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetPASSPHRASEOk() (*string, bool) {
	if o == nil || IsNil(o.PASSPHRASE) {
		return nil, false
	}
	return o.PASSPHRASE, true
}

// HasPASSPHRASE returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasPASSPHRASE() bool {
	if o != nil && !IsNil(o.PASSPHRASE) {
		return true
	}

	return false
}

// SetPASSPHRASE gets a reference to the given string and assigns it to the PASSPHRASE field.
func (o *SFTPConnectionAttributes) SetPASSPHRASE(v string) {
	o.PASSPHRASE = &v
}

// GetFILES_TO_GET returns the FILES_TO_GET field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetFILES_TO_GET() string {
	if o == nil || IsNil(o.FILES_TO_GET) {
		var ret string
		return ret
	}
	return *o.FILES_TO_GET
}

// GetFILES_TO_GETOk returns a tuple with the FILES_TO_GET field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetFILES_TO_GETOk() (*string, bool) {
	if o == nil || IsNil(o.FILES_TO_GET) {
		return nil, false
	}
	return o.FILES_TO_GET, true
}

// HasFILES_TO_GET returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasFILES_TO_GET() bool {
	if o != nil && !IsNil(o.FILES_TO_GET) {
		return true
	}

	return false
}

// SetFILES_TO_GET gets a reference to the given string and assigns it to the FILES_TO_GET field.
func (o *SFTPConnectionAttributes) SetFILES_TO_GET(v string) {
	o.FILES_TO_GET = &v
}

// GetFILES_TO_PUT returns the FILES_TO_PUT field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetFILES_TO_PUT() string {
	if o == nil || IsNil(o.FILES_TO_PUT) {
		var ret string
		return ret
	}
	return *o.FILES_TO_PUT
}

// GetFILES_TO_PUTOk returns a tuple with the FILES_TO_PUT field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetFILES_TO_PUTOk() (*string, bool) {
	if o == nil || IsNil(o.FILES_TO_PUT) {
		return nil, false
	}
	return o.FILES_TO_PUT, true
}

// HasFILES_TO_PUT returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasFILES_TO_PUT() bool {
	if o != nil && !IsNil(o.FILES_TO_PUT) {
		return true
	}

	return false
}

// SetFILES_TO_PUT gets a reference to the given string and assigns it to the FILES_TO_PUT field.
func (o *SFTPConnectionAttributes) SetFILES_TO_PUT(v string) {
	o.FILES_TO_PUT = &v
}

// GetPAM_CONFIG returns the PAM_CONFIG field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetPAM_CONFIG() string {
	if o == nil || IsNil(o.PAM_CONFIG) {
		var ret string
		return ret
	}
	return *o.PAM_CONFIG
}

// GetPAM_CONFIGOk returns a tuple with the PAM_CONFIG field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetPAM_CONFIGOk() (*string, bool) {
	if o == nil || IsNil(o.PAM_CONFIG) {
		return nil, false
	}
	return o.PAM_CONFIG, true
}

// HasPAM_CONFIG returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasPAM_CONFIG() bool {
	if o != nil && !IsNil(o.PAM_CONFIG) {
		return true
	}

	return false
}

// SetPAM_CONFIG gets a reference to the given string and assigns it to the PAM_CONFIG field.
func (o *SFTPConnectionAttributes) SetPAM_CONFIG(v string) {
	o.PAM_CONFIG = &v
}

// GetConnectionType returns the ConnectionType field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetConnectionType() string {
	if o == nil || IsNil(o.ConnectionType) {
		var ret string
		return ret
	}
	return *o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetConnectionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectionType) {
		return nil, false
	}
	return o.ConnectionType, true
}

// HasConnectionType returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasConnectionType() bool {
	if o != nil && !IsNil(o.ConnectionType) {
		return true
	}

	return false
}

// SetConnectionType gets a reference to the given string and assigns it to the ConnectionType field.
func (o *SFTPConnectionAttributes) SetConnectionType(v string) {
	o.ConnectionType = &v
}

// GetIsTimeoutSupported returns the IsTimeoutSupported field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetIsTimeoutSupported() bool {
	if o == nil || IsNil(o.IsTimeoutSupported) {
		var ret bool
		return ret
	}
	return *o.IsTimeoutSupported
}

// GetIsTimeoutSupportedOk returns a tuple with the IsTimeoutSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetIsTimeoutSupportedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTimeoutSupported) {
		return nil, false
	}
	return o.IsTimeoutSupported, true
}

// HasIsTimeoutSupported returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasIsTimeoutSupported() bool {
	if o != nil && !IsNil(o.IsTimeoutSupported) {
		return true
	}

	return false
}

// SetIsTimeoutSupported gets a reference to the given bool and assigns it to the IsTimeoutSupported field.
func (o *SFTPConnectionAttributes) SetIsTimeoutSupported(v bool) {
	o.IsTimeoutSupported = &v
}

// GetIsTimeoutConfigValidated returns the IsTimeoutConfigValidated field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetIsTimeoutConfigValidated() bool {
	if o == nil || IsNil(o.IsTimeoutConfigValidated) {
		var ret bool
		return ret
	}
	return *o.IsTimeoutConfigValidated
}

// GetIsTimeoutConfigValidatedOk returns a tuple with the IsTimeoutConfigValidated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetIsTimeoutConfigValidatedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTimeoutConfigValidated) {
		return nil, false
	}
	return o.IsTimeoutConfigValidated, true
}

// HasIsTimeoutConfigValidated returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasIsTimeoutConfigValidated() bool {
	if o != nil && !IsNil(o.IsTimeoutConfigValidated) {
		return true
	}

	return false
}

// SetIsTimeoutConfigValidated gets a reference to the given bool and assigns it to the IsTimeoutConfigValidated field.
func (o *SFTPConnectionAttributes) SetIsTimeoutConfigValidated(v bool) {
	o.IsTimeoutConfigValidated = &v
}

// GetConnectionTimeoutConfig returns the ConnectionTimeoutConfig field value if set, zero value otherwise.
func (o *SFTPConnectionAttributes) GetConnectionTimeoutConfig() ConnectionTimeoutConfig {
	if o == nil || IsNil(o.ConnectionTimeoutConfig) {
		var ret ConnectionTimeoutConfig
		return ret
	}
	return *o.ConnectionTimeoutConfig
}

// GetConnectionTimeoutConfigOk returns a tuple with the ConnectionTimeoutConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SFTPConnectionAttributes) GetConnectionTimeoutConfigOk() (*ConnectionTimeoutConfig, bool) {
	if o == nil || IsNil(o.ConnectionTimeoutConfig) {
		return nil, false
	}
	return o.ConnectionTimeoutConfig, true
}

// HasConnectionTimeoutConfig returns a boolean if a field has been set.
func (o *SFTPConnectionAttributes) HasConnectionTimeoutConfig() bool {
	if o != nil && !IsNil(o.ConnectionTimeoutConfig) {
		return true
	}

	return false
}

// SetConnectionTimeoutConfig gets a reference to the given ConnectionTimeoutConfig and assigns it to the ConnectionTimeoutConfig field.
func (o *SFTPConnectionAttributes) SetConnectionTimeoutConfig(v ConnectionTimeoutConfig) {
	o.ConnectionTimeoutConfig = &v
}

func (o SFTPConnectionAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SFTPConnectionAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HOST_NAME) {
		toSerialize["HOST_NAME"] = o.HOST_NAME
	}
	if !IsNil(o.PORT_NUMBER) {
		toSerialize["PORT_NUMBER"] = o.PORT_NUMBER
	}
	if !IsNil(o.USERNAME) {
		toSerialize["USERNAME"] = o.USERNAME
	}
	if !IsNil(o.AUTH_CREDENTIAL_TYPE) {
		toSerialize["AUTH_CREDENTIAL_TYPE"] = o.AUTH_CREDENTIAL_TYPE
	}
	if !IsNil(o.AUTH_CREDENTIAL_VALUE) {
		toSerialize["AUTH_CREDENTIAL_VALUE"] = o.AUTH_CREDENTIAL_VALUE
	}
	if !IsNil(o.PASSPHRASE) {
		toSerialize["PASSPHRASE"] = o.PASSPHRASE
	}
	if !IsNil(o.FILES_TO_GET) {
		toSerialize["FILES_TO_GET"] = o.FILES_TO_GET
	}
	if !IsNil(o.FILES_TO_PUT) {
		toSerialize["FILES_TO_PUT"] = o.FILES_TO_PUT
	}
	if !IsNil(o.PAM_CONFIG) {
		toSerialize["PAM_CONFIG"] = o.PAM_CONFIG
	}
	if !IsNil(o.ConnectionType) {
		toSerialize["connectionType"] = o.ConnectionType
	}
	if !IsNil(o.IsTimeoutSupported) {
		toSerialize["isTimeoutSupported"] = o.IsTimeoutSupported
	}
	if !IsNil(o.IsTimeoutConfigValidated) {
		toSerialize["isTimeoutConfigValidated"] = o.IsTimeoutConfigValidated
	}
	if !IsNil(o.ConnectionTimeoutConfig) {
		toSerialize["connectionTimeoutConfig"] = o.ConnectionTimeoutConfig
	}
	return toSerialize, nil
}

type NullableSFTPConnectionAttributes struct {
	value *SFTPConnectionAttributes
	isSet bool
}

func (v NullableSFTPConnectionAttributes) Get() *SFTPConnectionAttributes {
	return v.value
}

func (v *NullableSFTPConnectionAttributes) Set(val *SFTPConnectionAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSFTPConnectionAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSFTPConnectionAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSFTPConnectionAttributes(val *SFTPConnectionAttributes) *NullableSFTPConnectionAttributes {
	return &NullableSFTPConnectionAttributes{value: val, isSet: true}
}

func (v NullableSFTPConnectionAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSFTPConnectionAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
