/*
Entitlement Type Management API

API for managing entitlement types in Saviynt/SSM. - **Create Entitlement Type**: Creates a new entitlement type. - **Update Entitlement Type**: Updates an existing entitlement type. - **Get Entitlement Type List**: Returns a list of entitlement types based on search criteria.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entitlementtype

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateEntitlementTypeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEntitlementTypeRequest{}

// UpdateEntitlementTypeRequest struct for UpdateEntitlementTypeRequest
type UpdateEntitlementTypeRequest struct {
	// Name of the entitlement type
	Entitlementname string `json:"entitlementname"`
	// Display name for the entitlement.
	DisplayName *string `json:"displayName,omitempty"`
	// Name of the endpoint with which the entitlement type is associated
	Endpointname string `json:"endpointname"`
	// Description for the entitlement type
	Entitlementdescription *string `json:"entitlementdescription,omitempty"`
	// Workflow associated with the entitlement type
	Workflow *string `json:"workflow,omitempty"`
	// Enable entitlement to role sync
	EnableEntitlementToRoleSync *bool `json:"enableEntitlementToRoleSync,omitempty"`
	// Query to fetch available service accounts.
	AvailableQueryServiceAccount *string `json:"availableQueryServiceAccount,omitempty"`
	// Query to fetch selected service accounts.
	SelectedQueryServiceAccount *string `json:"selectedQueryServiceAccount,omitempty"`
	// Query used to determine requestable entitlements.
	ArsRequestableEntitlementQuery *string `json:"arsRequestableEntitlementQuery,omitempty"`
	// Query used to determine selected entitlements.
	ArsSelectedEntitlementQuery *string `json:"arsSelectedEntitlementQuery,omitempty"`
	// Indicates if the entitlement is certifiable.
	Certifiable *bool `json:"certifiable,omitempty"`
	// Action to be performed when a task is created.
	CreateTaskAction []string `json:"createTaskAction,omitempty"`
	// Configuration in JSON for handling request dates.
	RequestDatesConfJson *string `json:"requestDatesConfJson,omitempty"`
	// Ask For Start Date While Revoke Request
	StartDateInRevokeRequest *string `json:"startDateInRevokeRequest,omitempty"`
	// Ask For Start Date End Date While Request
	StartEndDateInRequest *string `json:"startEndDateInRequest,omitempty"`
	// Allow user to remove all entitlements in one request.
	AllowRemoveAllEntitlementInRequest *string `json:"allowRemoveAllEntitlementInRequest,omitempty"`
	// Index to determine the order of processing or display.
	Orderindex *int32 `json:"orderindex,omitempty"`
	// Flag indicating if this field is required in the request.
	Requiredinrequest *string `json:"requiredinrequest,omitempty"`
	// Flag indicating if this field is required in service request.
	Requiredinservicerequest *bool `json:"requiredinservicerequest,omitempty"`
	// Flag indicating if a hierarchy is required.
	Hiearchyrequired *string `json:"hiearchyrequired,omitempty"`
	// Show entitlement type on
	ShowEntTypeOn *string `json:"showEntTypeOn,omitempty"`
	// Enable provisioning priority
	EnableProvisioningPriority *bool `json:"enableProvisioningPriority,omitempty"`
	// Exclude Entitlements Assigned via Rule while Request
	ExcludeRuleAssgnEntsInRequest *bool `json:"excludeRuleAssgnEntsInRequest,omitempty"`
	// Recon
	Recon *bool `json:"recon,omitempty"`
	// Show on child
	Showonchild *bool `json:"showonchild,omitempty"`
	// Defines how the entitlement should be presented or requested.
	Requestoption *string `json:"requestoption,omitempty"`
	// Custom property 1
	Customproperty1 *string `json:"customproperty1,omitempty"`
	// Custom property 2
	Customproperty2 *string `json:"customproperty2,omitempty"`
	// Custom property 3
	Customproperty3 *string `json:"customproperty3,omitempty"`
	// Custom property 4
	Customproperty4 *string `json:"customproperty4,omitempty"`
	// Custom property 5
	Customproperty5 *string `json:"customproperty5,omitempty"`
	// Custom property 6
	Customproperty6 *string `json:"customproperty6,omitempty"`
	// Custom property 7
	Customproperty7 *string `json:"customproperty7,omitempty"`
	// Custom property 8
	Customproperty8 *string `json:"customproperty8,omitempty"`
	// Custom property 9
	Customproperty9 *string `json:"customproperty9,omitempty"`
	// Custom property 10
	Customproperty10 *string `json:"customproperty10,omitempty"`
	// Custom property 11
	Customproperty11 *string `json:"customproperty11,omitempty"`
	// Custom property 12
	Customproperty12 *string `json:"customproperty12,omitempty"`
	// Custom property 13
	Customproperty13 *string `json:"customproperty13,omitempty"`
	// Custom property 14
	Customproperty14 *string `json:"customproperty14,omitempty"`
	// Custom property 15
	Customproperty15 *string `json:"customproperty15,omitempty"`
	// Custom property 16
	Customproperty16 *string `json:"customproperty16,omitempty"`
	// Custom property 17
	Customproperty17 *string `json:"customproperty17,omitempty"`
	// Custom property 18
	Customproperty18 *string `json:"customproperty18,omitempty"`
	// Custom property 19
	Customproperty19 *string `json:"customproperty19,omitempty"`
	// Custom property 20
	Customproperty20 *string `json:"customproperty20,omitempty"`
	// Custom property 21
	Customproperty21 *string `json:"customproperty21,omitempty"`
	// Custom property 22
	Customproperty22 *string `json:"customproperty22,omitempty"`
	// Custom property 23
	Customproperty23 *string `json:"customproperty23,omitempty"`
	// Custom property 24
	Customproperty24 *string `json:"customproperty24,omitempty"`
	// Custom property 25
	Customproperty25 *string `json:"customproperty25,omitempty"`
	// Custom property 26
	Customproperty26 *string `json:"customproperty26,omitempty"`
	// Custom property 27
	Customproperty27 *string `json:"customproperty27,omitempty"`
	// Custom property 28
	Customproperty28 *string `json:"customproperty28,omitempty"`
	// Custom property 29
	Customproperty29 *string `json:"customproperty29,omitempty"`
	// Custom property 30
	Customproperty30 *string `json:"customproperty30,omitempty"`
	// Custom property 31
	Customproperty31 *string `json:"customproperty31,omitempty"`
	// Custom property 32
	Customproperty32 *string `json:"customproperty32,omitempty"`
	// Custom property 33
	Customproperty33 *string `json:"customproperty33,omitempty"`
	// Custom property 34
	Customproperty34 *string `json:"customproperty34,omitempty"`
	// Custom property 35
	Customproperty35 *string `json:"customproperty35,omitempty"`
	// Custom property 36
	Customproperty36 *string `json:"customproperty36,omitempty"`
	// Custom property 37
	Customproperty37 *string `json:"customproperty37,omitempty"`
	// Custom property 38
	Customproperty38 *string `json:"customproperty38,omitempty"`
	// Custom property 39
	Customproperty39 *string `json:"customproperty39,omitempty"`
	// Custom property 40
	Customproperty40 *string `json:"customproperty40,omitempty"`
}

type _UpdateEntitlementTypeRequest UpdateEntitlementTypeRequest

// NewUpdateEntitlementTypeRequest instantiates a new UpdateEntitlementTypeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEntitlementTypeRequest(entitlementname string, endpointname string) *UpdateEntitlementTypeRequest {
	this := UpdateEntitlementTypeRequest{}
	this.Entitlementname = entitlementname
	this.Endpointname = endpointname
	return &this
}

// NewUpdateEntitlementTypeRequestWithDefaults instantiates a new UpdateEntitlementTypeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEntitlementTypeRequestWithDefaults() *UpdateEntitlementTypeRequest {
	this := UpdateEntitlementTypeRequest{}
	return &this
}

// GetEntitlementname returns the Entitlementname field value
func (o *UpdateEntitlementTypeRequest) GetEntitlementname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entitlementname
}

// GetEntitlementnameOk returns a tuple with the Entitlementname field value
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetEntitlementnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entitlementname, true
}

// SetEntitlementname sets field value
func (o *UpdateEntitlementTypeRequest) SetEntitlementname(v string) {
	o.Entitlementname = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *UpdateEntitlementTypeRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetEndpointname returns the Endpointname field value
func (o *UpdateEntitlementTypeRequest) GetEndpointname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpointname
}

// GetEndpointnameOk returns a tuple with the Endpointname field value
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetEndpointnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpointname, true
}

// SetEndpointname sets field value
func (o *UpdateEntitlementTypeRequest) SetEndpointname(v string) {
	o.Endpointname = v
}

// GetEntitlementdescription returns the Entitlementdescription field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetEntitlementdescription() string {
	if o == nil || IsNil(o.Entitlementdescription) {
		var ret string
		return ret
	}
	return *o.Entitlementdescription
}

// GetEntitlementdescriptionOk returns a tuple with the Entitlementdescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetEntitlementdescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Entitlementdescription) {
		return nil, false
	}
	return o.Entitlementdescription, true
}

// HasEntitlementdescription returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasEntitlementdescription() bool {
	if o != nil && !IsNil(o.Entitlementdescription) {
		return true
	}

	return false
}

// SetEntitlementdescription gets a reference to the given string and assigns it to the Entitlementdescription field.
func (o *UpdateEntitlementTypeRequest) SetEntitlementdescription(v string) {
	o.Entitlementdescription = &v
}

// GetWorkflow returns the Workflow field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetWorkflow() string {
	if o == nil || IsNil(o.Workflow) {
		var ret string
		return ret
	}
	return *o.Workflow
}

// GetWorkflowOk returns a tuple with the Workflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetWorkflowOk() (*string, bool) {
	if o == nil || IsNil(o.Workflow) {
		return nil, false
	}
	return o.Workflow, true
}

// HasWorkflow returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasWorkflow() bool {
	if o != nil && !IsNil(o.Workflow) {
		return true
	}

	return false
}

// SetWorkflow gets a reference to the given string and assigns it to the Workflow field.
func (o *UpdateEntitlementTypeRequest) SetWorkflow(v string) {
	o.Workflow = &v
}

// GetEnableEntitlementToRoleSync returns the EnableEntitlementToRoleSync field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetEnableEntitlementToRoleSync() bool {
	if o == nil || IsNil(o.EnableEntitlementToRoleSync) {
		var ret bool
		return ret
	}
	return *o.EnableEntitlementToRoleSync
}

// GetEnableEntitlementToRoleSyncOk returns a tuple with the EnableEntitlementToRoleSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetEnableEntitlementToRoleSyncOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableEntitlementToRoleSync) {
		return nil, false
	}
	return o.EnableEntitlementToRoleSync, true
}

// HasEnableEntitlementToRoleSync returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasEnableEntitlementToRoleSync() bool {
	if o != nil && !IsNil(o.EnableEntitlementToRoleSync) {
		return true
	}

	return false
}

// SetEnableEntitlementToRoleSync gets a reference to the given bool and assigns it to the EnableEntitlementToRoleSync field.
func (o *UpdateEntitlementTypeRequest) SetEnableEntitlementToRoleSync(v bool) {
	o.EnableEntitlementToRoleSync = &v
}

// GetAvailableQueryServiceAccount returns the AvailableQueryServiceAccount field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetAvailableQueryServiceAccount() string {
	if o == nil || IsNil(o.AvailableQueryServiceAccount) {
		var ret string
		return ret
	}
	return *o.AvailableQueryServiceAccount
}

// GetAvailableQueryServiceAccountOk returns a tuple with the AvailableQueryServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetAvailableQueryServiceAccountOk() (*string, bool) {
	if o == nil || IsNil(o.AvailableQueryServiceAccount) {
		return nil, false
	}
	return o.AvailableQueryServiceAccount, true
}

// HasAvailableQueryServiceAccount returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasAvailableQueryServiceAccount() bool {
	if o != nil && !IsNil(o.AvailableQueryServiceAccount) {
		return true
	}

	return false
}

// SetAvailableQueryServiceAccount gets a reference to the given string and assigns it to the AvailableQueryServiceAccount field.
func (o *UpdateEntitlementTypeRequest) SetAvailableQueryServiceAccount(v string) {
	o.AvailableQueryServiceAccount = &v
}

// GetSelectedQueryServiceAccount returns the SelectedQueryServiceAccount field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetSelectedQueryServiceAccount() string {
	if o == nil || IsNil(o.SelectedQueryServiceAccount) {
		var ret string
		return ret
	}
	return *o.SelectedQueryServiceAccount
}

// GetSelectedQueryServiceAccountOk returns a tuple with the SelectedQueryServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetSelectedQueryServiceAccountOk() (*string, bool) {
	if o == nil || IsNil(o.SelectedQueryServiceAccount) {
		return nil, false
	}
	return o.SelectedQueryServiceAccount, true
}

// HasSelectedQueryServiceAccount returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasSelectedQueryServiceAccount() bool {
	if o != nil && !IsNil(o.SelectedQueryServiceAccount) {
		return true
	}

	return false
}

// SetSelectedQueryServiceAccount gets a reference to the given string and assigns it to the SelectedQueryServiceAccount field.
func (o *UpdateEntitlementTypeRequest) SetSelectedQueryServiceAccount(v string) {
	o.SelectedQueryServiceAccount = &v
}

// GetArsRequestableEntitlementQuery returns the ArsRequestableEntitlementQuery field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetArsRequestableEntitlementQuery() string {
	if o == nil || IsNil(o.ArsRequestableEntitlementQuery) {
		var ret string
		return ret
	}
	return *o.ArsRequestableEntitlementQuery
}

// GetArsRequestableEntitlementQueryOk returns a tuple with the ArsRequestableEntitlementQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetArsRequestableEntitlementQueryOk() (*string, bool) {
	if o == nil || IsNil(o.ArsRequestableEntitlementQuery) {
		return nil, false
	}
	return o.ArsRequestableEntitlementQuery, true
}

// HasArsRequestableEntitlementQuery returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasArsRequestableEntitlementQuery() bool {
	if o != nil && !IsNil(o.ArsRequestableEntitlementQuery) {
		return true
	}

	return false
}

// SetArsRequestableEntitlementQuery gets a reference to the given string and assigns it to the ArsRequestableEntitlementQuery field.
func (o *UpdateEntitlementTypeRequest) SetArsRequestableEntitlementQuery(v string) {
	o.ArsRequestableEntitlementQuery = &v
}

// GetArsSelectedEntitlementQuery returns the ArsSelectedEntitlementQuery field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetArsSelectedEntitlementQuery() string {
	if o == nil || IsNil(o.ArsSelectedEntitlementQuery) {
		var ret string
		return ret
	}
	return *o.ArsSelectedEntitlementQuery
}

// GetArsSelectedEntitlementQueryOk returns a tuple with the ArsSelectedEntitlementQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetArsSelectedEntitlementQueryOk() (*string, bool) {
	if o == nil || IsNil(o.ArsSelectedEntitlementQuery) {
		return nil, false
	}
	return o.ArsSelectedEntitlementQuery, true
}

// HasArsSelectedEntitlementQuery returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasArsSelectedEntitlementQuery() bool {
	if o != nil && !IsNil(o.ArsSelectedEntitlementQuery) {
		return true
	}

	return false
}

// SetArsSelectedEntitlementQuery gets a reference to the given string and assigns it to the ArsSelectedEntitlementQuery field.
func (o *UpdateEntitlementTypeRequest) SetArsSelectedEntitlementQuery(v string) {
	o.ArsSelectedEntitlementQuery = &v
}

// GetCertifiable returns the Certifiable field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCertifiable() bool {
	if o == nil || IsNil(o.Certifiable) {
		var ret bool
		return ret
	}
	return *o.Certifiable
}

// GetCertifiableOk returns a tuple with the Certifiable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCertifiableOk() (*bool, bool) {
	if o == nil || IsNil(o.Certifiable) {
		return nil, false
	}
	return o.Certifiable, true
}

// HasCertifiable returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCertifiable() bool {
	if o != nil && !IsNil(o.Certifiable) {
		return true
	}

	return false
}

// SetCertifiable gets a reference to the given bool and assigns it to the Certifiable field.
func (o *UpdateEntitlementTypeRequest) SetCertifiable(v bool) {
	o.Certifiable = &v
}

// GetCreateTaskAction returns the CreateTaskAction field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCreateTaskAction() []string {
	if o == nil || IsNil(o.CreateTaskAction) {
		var ret []string
		return ret
	}
	return o.CreateTaskAction
}

// GetCreateTaskActionOk returns a tuple with the CreateTaskAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCreateTaskActionOk() ([]string, bool) {
	if o == nil || IsNil(o.CreateTaskAction) {
		return nil, false
	}
	return o.CreateTaskAction, true
}

// HasCreateTaskAction returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCreateTaskAction() bool {
	if o != nil && !IsNil(o.CreateTaskAction) {
		return true
	}

	return false
}

// SetCreateTaskAction gets a reference to the given []string and assigns it to the CreateTaskAction field.
func (o *UpdateEntitlementTypeRequest) SetCreateTaskAction(v []string) {
	o.CreateTaskAction = v
}

// GetRequestDatesConfJson returns the RequestDatesConfJson field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetRequestDatesConfJson() string {
	if o == nil || IsNil(o.RequestDatesConfJson) {
		var ret string
		return ret
	}
	return *o.RequestDatesConfJson
}

// GetRequestDatesConfJsonOk returns a tuple with the RequestDatesConfJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetRequestDatesConfJsonOk() (*string, bool) {
	if o == nil || IsNil(o.RequestDatesConfJson) {
		return nil, false
	}
	return o.RequestDatesConfJson, true
}

// HasRequestDatesConfJson returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasRequestDatesConfJson() bool {
	if o != nil && !IsNil(o.RequestDatesConfJson) {
		return true
	}

	return false
}

// SetRequestDatesConfJson gets a reference to the given string and assigns it to the RequestDatesConfJson field.
func (o *UpdateEntitlementTypeRequest) SetRequestDatesConfJson(v string) {
	o.RequestDatesConfJson = &v
}

// GetStartDateInRevokeRequest returns the StartDateInRevokeRequest field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetStartDateInRevokeRequest() string {
	if o == nil || IsNil(o.StartDateInRevokeRequest) {
		var ret string
		return ret
	}
	return *o.StartDateInRevokeRequest
}

// GetStartDateInRevokeRequestOk returns a tuple with the StartDateInRevokeRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetStartDateInRevokeRequestOk() (*string, bool) {
	if o == nil || IsNil(o.StartDateInRevokeRequest) {
		return nil, false
	}
	return o.StartDateInRevokeRequest, true
}

// HasStartDateInRevokeRequest returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasStartDateInRevokeRequest() bool {
	if o != nil && !IsNil(o.StartDateInRevokeRequest) {
		return true
	}

	return false
}

// SetStartDateInRevokeRequest gets a reference to the given string and assigns it to the StartDateInRevokeRequest field.
func (o *UpdateEntitlementTypeRequest) SetStartDateInRevokeRequest(v string) {
	o.StartDateInRevokeRequest = &v
}

// GetStartEndDateInRequest returns the StartEndDateInRequest field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetStartEndDateInRequest() string {
	if o == nil || IsNil(o.StartEndDateInRequest) {
		var ret string
		return ret
	}
	return *o.StartEndDateInRequest
}

// GetStartEndDateInRequestOk returns a tuple with the StartEndDateInRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetStartEndDateInRequestOk() (*string, bool) {
	if o == nil || IsNil(o.StartEndDateInRequest) {
		return nil, false
	}
	return o.StartEndDateInRequest, true
}

// HasStartEndDateInRequest returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasStartEndDateInRequest() bool {
	if o != nil && !IsNil(o.StartEndDateInRequest) {
		return true
	}

	return false
}

// SetStartEndDateInRequest gets a reference to the given string and assigns it to the StartEndDateInRequest field.
func (o *UpdateEntitlementTypeRequest) SetStartEndDateInRequest(v string) {
	o.StartEndDateInRequest = &v
}

// GetAllowRemoveAllEntitlementInRequest returns the AllowRemoveAllEntitlementInRequest field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetAllowRemoveAllEntitlementInRequest() string {
	if o == nil || IsNil(o.AllowRemoveAllEntitlementInRequest) {
		var ret string
		return ret
	}
	return *o.AllowRemoveAllEntitlementInRequest
}

// GetAllowRemoveAllEntitlementInRequestOk returns a tuple with the AllowRemoveAllEntitlementInRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetAllowRemoveAllEntitlementInRequestOk() (*string, bool) {
	if o == nil || IsNil(o.AllowRemoveAllEntitlementInRequest) {
		return nil, false
	}
	return o.AllowRemoveAllEntitlementInRequest, true
}

// HasAllowRemoveAllEntitlementInRequest returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasAllowRemoveAllEntitlementInRequest() bool {
	if o != nil && !IsNil(o.AllowRemoveAllEntitlementInRequest) {
		return true
	}

	return false
}

// SetAllowRemoveAllEntitlementInRequest gets a reference to the given string and assigns it to the AllowRemoveAllEntitlementInRequest field.
func (o *UpdateEntitlementTypeRequest) SetAllowRemoveAllEntitlementInRequest(v string) {
	o.AllowRemoveAllEntitlementInRequest = &v
}

// GetOrderindex returns the Orderindex field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetOrderindex() int32 {
	if o == nil || IsNil(o.Orderindex) {
		var ret int32
		return ret
	}
	return *o.Orderindex
}

// GetOrderindexOk returns a tuple with the Orderindex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetOrderindexOk() (*int32, bool) {
	if o == nil || IsNil(o.Orderindex) {
		return nil, false
	}
	return o.Orderindex, true
}

// HasOrderindex returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasOrderindex() bool {
	if o != nil && !IsNil(o.Orderindex) {
		return true
	}

	return false
}

// SetOrderindex gets a reference to the given int32 and assigns it to the Orderindex field.
func (o *UpdateEntitlementTypeRequest) SetOrderindex(v int32) {
	o.Orderindex = &v
}

// GetRequiredinrequest returns the Requiredinrequest field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetRequiredinrequest() string {
	if o == nil || IsNil(o.Requiredinrequest) {
		var ret string
		return ret
	}
	return *o.Requiredinrequest
}

// GetRequiredinrequestOk returns a tuple with the Requiredinrequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetRequiredinrequestOk() (*string, bool) {
	if o == nil || IsNil(o.Requiredinrequest) {
		return nil, false
	}
	return o.Requiredinrequest, true
}

// HasRequiredinrequest returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasRequiredinrequest() bool {
	if o != nil && !IsNil(o.Requiredinrequest) {
		return true
	}

	return false
}

// SetRequiredinrequest gets a reference to the given string and assigns it to the Requiredinrequest field.
func (o *UpdateEntitlementTypeRequest) SetRequiredinrequest(v string) {
	o.Requiredinrequest = &v
}

// GetRequiredinservicerequest returns the Requiredinservicerequest field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetRequiredinservicerequest() bool {
	if o == nil || IsNil(o.Requiredinservicerequest) {
		var ret bool
		return ret
	}
	return *o.Requiredinservicerequest
}

// GetRequiredinservicerequestOk returns a tuple with the Requiredinservicerequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetRequiredinservicerequestOk() (*bool, bool) {
	if o == nil || IsNil(o.Requiredinservicerequest) {
		return nil, false
	}
	return o.Requiredinservicerequest, true
}

// HasRequiredinservicerequest returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasRequiredinservicerequest() bool {
	if o != nil && !IsNil(o.Requiredinservicerequest) {
		return true
	}

	return false
}

// SetRequiredinservicerequest gets a reference to the given bool and assigns it to the Requiredinservicerequest field.
func (o *UpdateEntitlementTypeRequest) SetRequiredinservicerequest(v bool) {
	o.Requiredinservicerequest = &v
}

// GetHiearchyrequired returns the Hiearchyrequired field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetHiearchyrequired() string {
	if o == nil || IsNil(o.Hiearchyrequired) {
		var ret string
		return ret
	}
	return *o.Hiearchyrequired
}

// GetHiearchyrequiredOk returns a tuple with the Hiearchyrequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetHiearchyrequiredOk() (*string, bool) {
	if o == nil || IsNil(o.Hiearchyrequired) {
		return nil, false
	}
	return o.Hiearchyrequired, true
}

// HasHiearchyrequired returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasHiearchyrequired() bool {
	if o != nil && !IsNil(o.Hiearchyrequired) {
		return true
	}

	return false
}

// SetHiearchyrequired gets a reference to the given string and assigns it to the Hiearchyrequired field.
func (o *UpdateEntitlementTypeRequest) SetHiearchyrequired(v string) {
	o.Hiearchyrequired = &v
}

// GetShowEntTypeOn returns the ShowEntTypeOn field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetShowEntTypeOn() string {
	if o == nil || IsNil(o.ShowEntTypeOn) {
		var ret string
		return ret
	}
	return *o.ShowEntTypeOn
}

// GetShowEntTypeOnOk returns a tuple with the ShowEntTypeOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetShowEntTypeOnOk() (*string, bool) {
	if o == nil || IsNil(o.ShowEntTypeOn) {
		return nil, false
	}
	return o.ShowEntTypeOn, true
}

// HasShowEntTypeOn returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasShowEntTypeOn() bool {
	if o != nil && !IsNil(o.ShowEntTypeOn) {
		return true
	}

	return false
}

// SetShowEntTypeOn gets a reference to the given string and assigns it to the ShowEntTypeOn field.
func (o *UpdateEntitlementTypeRequest) SetShowEntTypeOn(v string) {
	o.ShowEntTypeOn = &v
}

// GetEnableProvisioningPriority returns the EnableProvisioningPriority field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetEnableProvisioningPriority() bool {
	if o == nil || IsNil(o.EnableProvisioningPriority) {
		var ret bool
		return ret
	}
	return *o.EnableProvisioningPriority
}

// GetEnableProvisioningPriorityOk returns a tuple with the EnableProvisioningPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetEnableProvisioningPriorityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableProvisioningPriority) {
		return nil, false
	}
	return o.EnableProvisioningPriority, true
}

// HasEnableProvisioningPriority returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasEnableProvisioningPriority() bool {
	if o != nil && !IsNil(o.EnableProvisioningPriority) {
		return true
	}

	return false
}

// SetEnableProvisioningPriority gets a reference to the given bool and assigns it to the EnableProvisioningPriority field.
func (o *UpdateEntitlementTypeRequest) SetEnableProvisioningPriority(v bool) {
	o.EnableProvisioningPriority = &v
}

// GetExcludeRuleAssgnEntsInRequest returns the ExcludeRuleAssgnEntsInRequest field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetExcludeRuleAssgnEntsInRequest() bool {
	if o == nil || IsNil(o.ExcludeRuleAssgnEntsInRequest) {
		var ret bool
		return ret
	}
	return *o.ExcludeRuleAssgnEntsInRequest
}

// GetExcludeRuleAssgnEntsInRequestOk returns a tuple with the ExcludeRuleAssgnEntsInRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetExcludeRuleAssgnEntsInRequestOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeRuleAssgnEntsInRequest) {
		return nil, false
	}
	return o.ExcludeRuleAssgnEntsInRequest, true
}

// HasExcludeRuleAssgnEntsInRequest returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasExcludeRuleAssgnEntsInRequest() bool {
	if o != nil && !IsNil(o.ExcludeRuleAssgnEntsInRequest) {
		return true
	}

	return false
}

// SetExcludeRuleAssgnEntsInRequest gets a reference to the given bool and assigns it to the ExcludeRuleAssgnEntsInRequest field.
func (o *UpdateEntitlementTypeRequest) SetExcludeRuleAssgnEntsInRequest(v bool) {
	o.ExcludeRuleAssgnEntsInRequest = &v
}

// GetRecon returns the Recon field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetRecon() bool {
	if o == nil || IsNil(o.Recon) {
		var ret bool
		return ret
	}
	return *o.Recon
}

// GetReconOk returns a tuple with the Recon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetReconOk() (*bool, bool) {
	if o == nil || IsNil(o.Recon) {
		return nil, false
	}
	return o.Recon, true
}

// HasRecon returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasRecon() bool {
	if o != nil && !IsNil(o.Recon) {
		return true
	}

	return false
}

// SetRecon gets a reference to the given bool and assigns it to the Recon field.
func (o *UpdateEntitlementTypeRequest) SetRecon(v bool) {
	o.Recon = &v
}

// GetShowonchild returns the Showonchild field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetShowonchild() bool {
	if o == nil || IsNil(o.Showonchild) {
		var ret bool
		return ret
	}
	return *o.Showonchild
}

// GetShowonchildOk returns a tuple with the Showonchild field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetShowonchildOk() (*bool, bool) {
	if o == nil || IsNil(o.Showonchild) {
		return nil, false
	}
	return o.Showonchild, true
}

// HasShowonchild returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasShowonchild() bool {
	if o != nil && !IsNil(o.Showonchild) {
		return true
	}

	return false
}

// SetShowonchild gets a reference to the given bool and assigns it to the Showonchild field.
func (o *UpdateEntitlementTypeRequest) SetShowonchild(v bool) {
	o.Showonchild = &v
}

// GetRequestoption returns the Requestoption field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetRequestoption() string {
	if o == nil || IsNil(o.Requestoption) {
		var ret string
		return ret
	}
	return *o.Requestoption
}

// GetRequestoptionOk returns a tuple with the Requestoption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetRequestoptionOk() (*string, bool) {
	if o == nil || IsNil(o.Requestoption) {
		return nil, false
	}
	return o.Requestoption, true
}

// HasRequestoption returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasRequestoption() bool {
	if o != nil && !IsNil(o.Requestoption) {
		return true
	}

	return false
}

// SetRequestoption gets a reference to the given string and assigns it to the Requestoption field.
func (o *UpdateEntitlementTypeRequest) SetRequestoption(v string) {
	o.Requestoption = &v
}

// GetCustomproperty1 returns the Customproperty1 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty1() string {
	if o == nil || IsNil(o.Customproperty1) {
		var ret string
		return ret
	}
	return *o.Customproperty1
}

// GetCustomproperty1Ok returns a tuple with the Customproperty1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty1Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty1) {
		return nil, false
	}
	return o.Customproperty1, true
}

// HasCustomproperty1 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty1() bool {
	if o != nil && !IsNil(o.Customproperty1) {
		return true
	}

	return false
}

// SetCustomproperty1 gets a reference to the given string and assigns it to the Customproperty1 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty1(v string) {
	o.Customproperty1 = &v
}

// GetCustomproperty2 returns the Customproperty2 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty2() string {
	if o == nil || IsNil(o.Customproperty2) {
		var ret string
		return ret
	}
	return *o.Customproperty2
}

// GetCustomproperty2Ok returns a tuple with the Customproperty2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty2Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty2) {
		return nil, false
	}
	return o.Customproperty2, true
}

// HasCustomproperty2 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty2() bool {
	if o != nil && !IsNil(o.Customproperty2) {
		return true
	}

	return false
}

// SetCustomproperty2 gets a reference to the given string and assigns it to the Customproperty2 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty2(v string) {
	o.Customproperty2 = &v
}

// GetCustomproperty3 returns the Customproperty3 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty3() string {
	if o == nil || IsNil(o.Customproperty3) {
		var ret string
		return ret
	}
	return *o.Customproperty3
}

// GetCustomproperty3Ok returns a tuple with the Customproperty3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty3Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty3) {
		return nil, false
	}
	return o.Customproperty3, true
}

// HasCustomproperty3 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty3() bool {
	if o != nil && !IsNil(o.Customproperty3) {
		return true
	}

	return false
}

// SetCustomproperty3 gets a reference to the given string and assigns it to the Customproperty3 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty3(v string) {
	o.Customproperty3 = &v
}

// GetCustomproperty4 returns the Customproperty4 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty4() string {
	if o == nil || IsNil(o.Customproperty4) {
		var ret string
		return ret
	}
	return *o.Customproperty4
}

// GetCustomproperty4Ok returns a tuple with the Customproperty4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty4Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty4) {
		return nil, false
	}
	return o.Customproperty4, true
}

// HasCustomproperty4 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty4() bool {
	if o != nil && !IsNil(o.Customproperty4) {
		return true
	}

	return false
}

// SetCustomproperty4 gets a reference to the given string and assigns it to the Customproperty4 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty4(v string) {
	o.Customproperty4 = &v
}

// GetCustomproperty5 returns the Customproperty5 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty5() string {
	if o == nil || IsNil(o.Customproperty5) {
		var ret string
		return ret
	}
	return *o.Customproperty5
}

// GetCustomproperty5Ok returns a tuple with the Customproperty5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty5Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty5) {
		return nil, false
	}
	return o.Customproperty5, true
}

// HasCustomproperty5 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty5() bool {
	if o != nil && !IsNil(o.Customproperty5) {
		return true
	}

	return false
}

// SetCustomproperty5 gets a reference to the given string and assigns it to the Customproperty5 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty5(v string) {
	o.Customproperty5 = &v
}

// GetCustomproperty6 returns the Customproperty6 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty6() string {
	if o == nil || IsNil(o.Customproperty6) {
		var ret string
		return ret
	}
	return *o.Customproperty6
}

// GetCustomproperty6Ok returns a tuple with the Customproperty6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty6Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty6) {
		return nil, false
	}
	return o.Customproperty6, true
}

// HasCustomproperty6 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty6() bool {
	if o != nil && !IsNil(o.Customproperty6) {
		return true
	}

	return false
}

// SetCustomproperty6 gets a reference to the given string and assigns it to the Customproperty6 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty6(v string) {
	o.Customproperty6 = &v
}

// GetCustomproperty7 returns the Customproperty7 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty7() string {
	if o == nil || IsNil(o.Customproperty7) {
		var ret string
		return ret
	}
	return *o.Customproperty7
}

// GetCustomproperty7Ok returns a tuple with the Customproperty7 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty7Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty7) {
		return nil, false
	}
	return o.Customproperty7, true
}

// HasCustomproperty7 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty7() bool {
	if o != nil && !IsNil(o.Customproperty7) {
		return true
	}

	return false
}

// SetCustomproperty7 gets a reference to the given string and assigns it to the Customproperty7 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty7(v string) {
	o.Customproperty7 = &v
}

// GetCustomproperty8 returns the Customproperty8 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty8() string {
	if o == nil || IsNil(o.Customproperty8) {
		var ret string
		return ret
	}
	return *o.Customproperty8
}

// GetCustomproperty8Ok returns a tuple with the Customproperty8 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty8Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty8) {
		return nil, false
	}
	return o.Customproperty8, true
}

// HasCustomproperty8 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty8() bool {
	if o != nil && !IsNil(o.Customproperty8) {
		return true
	}

	return false
}

// SetCustomproperty8 gets a reference to the given string and assigns it to the Customproperty8 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty8(v string) {
	o.Customproperty8 = &v
}

// GetCustomproperty9 returns the Customproperty9 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty9() string {
	if o == nil || IsNil(o.Customproperty9) {
		var ret string
		return ret
	}
	return *o.Customproperty9
}

// GetCustomproperty9Ok returns a tuple with the Customproperty9 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty9Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty9) {
		return nil, false
	}
	return o.Customproperty9, true
}

// HasCustomproperty9 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty9() bool {
	if o != nil && !IsNil(o.Customproperty9) {
		return true
	}

	return false
}

// SetCustomproperty9 gets a reference to the given string and assigns it to the Customproperty9 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty9(v string) {
	o.Customproperty9 = &v
}

// GetCustomproperty10 returns the Customproperty10 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty10() string {
	if o == nil || IsNil(o.Customproperty10) {
		var ret string
		return ret
	}
	return *o.Customproperty10
}

// GetCustomproperty10Ok returns a tuple with the Customproperty10 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty10Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty10) {
		return nil, false
	}
	return o.Customproperty10, true
}

// HasCustomproperty10 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty10() bool {
	if o != nil && !IsNil(o.Customproperty10) {
		return true
	}

	return false
}

// SetCustomproperty10 gets a reference to the given string and assigns it to the Customproperty10 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty10(v string) {
	o.Customproperty10 = &v
}

// GetCustomproperty11 returns the Customproperty11 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty11() string {
	if o == nil || IsNil(o.Customproperty11) {
		var ret string
		return ret
	}
	return *o.Customproperty11
}

// GetCustomproperty11Ok returns a tuple with the Customproperty11 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty11Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty11) {
		return nil, false
	}
	return o.Customproperty11, true
}

// HasCustomproperty11 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty11() bool {
	if o != nil && !IsNil(o.Customproperty11) {
		return true
	}

	return false
}

// SetCustomproperty11 gets a reference to the given string and assigns it to the Customproperty11 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty11(v string) {
	o.Customproperty11 = &v
}

// GetCustomproperty12 returns the Customproperty12 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty12() string {
	if o == nil || IsNil(o.Customproperty12) {
		var ret string
		return ret
	}
	return *o.Customproperty12
}

// GetCustomproperty12Ok returns a tuple with the Customproperty12 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty12Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty12) {
		return nil, false
	}
	return o.Customproperty12, true
}

// HasCustomproperty12 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty12() bool {
	if o != nil && !IsNil(o.Customproperty12) {
		return true
	}

	return false
}

// SetCustomproperty12 gets a reference to the given string and assigns it to the Customproperty12 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty12(v string) {
	o.Customproperty12 = &v
}

// GetCustomproperty13 returns the Customproperty13 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty13() string {
	if o == nil || IsNil(o.Customproperty13) {
		var ret string
		return ret
	}
	return *o.Customproperty13
}

// GetCustomproperty13Ok returns a tuple with the Customproperty13 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty13Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty13) {
		return nil, false
	}
	return o.Customproperty13, true
}

// HasCustomproperty13 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty13() bool {
	if o != nil && !IsNil(o.Customproperty13) {
		return true
	}

	return false
}

// SetCustomproperty13 gets a reference to the given string and assigns it to the Customproperty13 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty13(v string) {
	o.Customproperty13 = &v
}

// GetCustomproperty14 returns the Customproperty14 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty14() string {
	if o == nil || IsNil(o.Customproperty14) {
		var ret string
		return ret
	}
	return *o.Customproperty14
}

// GetCustomproperty14Ok returns a tuple with the Customproperty14 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty14Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty14) {
		return nil, false
	}
	return o.Customproperty14, true
}

// HasCustomproperty14 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty14() bool {
	if o != nil && !IsNil(o.Customproperty14) {
		return true
	}

	return false
}

// SetCustomproperty14 gets a reference to the given string and assigns it to the Customproperty14 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty14(v string) {
	o.Customproperty14 = &v
}

// GetCustomproperty15 returns the Customproperty15 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty15() string {
	if o == nil || IsNil(o.Customproperty15) {
		var ret string
		return ret
	}
	return *o.Customproperty15
}

// GetCustomproperty15Ok returns a tuple with the Customproperty15 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty15Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty15) {
		return nil, false
	}
	return o.Customproperty15, true
}

// HasCustomproperty15 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty15() bool {
	if o != nil && !IsNil(o.Customproperty15) {
		return true
	}

	return false
}

// SetCustomproperty15 gets a reference to the given string and assigns it to the Customproperty15 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty15(v string) {
	o.Customproperty15 = &v
}

// GetCustomproperty16 returns the Customproperty16 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty16() string {
	if o == nil || IsNil(o.Customproperty16) {
		var ret string
		return ret
	}
	return *o.Customproperty16
}

// GetCustomproperty16Ok returns a tuple with the Customproperty16 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty16Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty16) {
		return nil, false
	}
	return o.Customproperty16, true
}

// HasCustomproperty16 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty16() bool {
	if o != nil && !IsNil(o.Customproperty16) {
		return true
	}

	return false
}

// SetCustomproperty16 gets a reference to the given string and assigns it to the Customproperty16 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty16(v string) {
	o.Customproperty16 = &v
}

// GetCustomproperty17 returns the Customproperty17 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty17() string {
	if o == nil || IsNil(o.Customproperty17) {
		var ret string
		return ret
	}
	return *o.Customproperty17
}

// GetCustomproperty17Ok returns a tuple with the Customproperty17 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty17Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty17) {
		return nil, false
	}
	return o.Customproperty17, true
}

// HasCustomproperty17 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty17() bool {
	if o != nil && !IsNil(o.Customproperty17) {
		return true
	}

	return false
}

// SetCustomproperty17 gets a reference to the given string and assigns it to the Customproperty17 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty17(v string) {
	o.Customproperty17 = &v
}

// GetCustomproperty18 returns the Customproperty18 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty18() string {
	if o == nil || IsNil(o.Customproperty18) {
		var ret string
		return ret
	}
	return *o.Customproperty18
}

// GetCustomproperty18Ok returns a tuple with the Customproperty18 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty18Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty18) {
		return nil, false
	}
	return o.Customproperty18, true
}

// HasCustomproperty18 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty18() bool {
	if o != nil && !IsNil(o.Customproperty18) {
		return true
	}

	return false
}

// SetCustomproperty18 gets a reference to the given string and assigns it to the Customproperty18 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty18(v string) {
	o.Customproperty18 = &v
}

// GetCustomproperty19 returns the Customproperty19 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty19() string {
	if o == nil || IsNil(o.Customproperty19) {
		var ret string
		return ret
	}
	return *o.Customproperty19
}

// GetCustomproperty19Ok returns a tuple with the Customproperty19 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty19Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty19) {
		return nil, false
	}
	return o.Customproperty19, true
}

// HasCustomproperty19 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty19() bool {
	if o != nil && !IsNil(o.Customproperty19) {
		return true
	}

	return false
}

// SetCustomproperty19 gets a reference to the given string and assigns it to the Customproperty19 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty19(v string) {
	o.Customproperty19 = &v
}

// GetCustomproperty20 returns the Customproperty20 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty20() string {
	if o == nil || IsNil(o.Customproperty20) {
		var ret string
		return ret
	}
	return *o.Customproperty20
}

// GetCustomproperty20Ok returns a tuple with the Customproperty20 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty20Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty20) {
		return nil, false
	}
	return o.Customproperty20, true
}

// HasCustomproperty20 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty20() bool {
	if o != nil && !IsNil(o.Customproperty20) {
		return true
	}

	return false
}

// SetCustomproperty20 gets a reference to the given string and assigns it to the Customproperty20 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty20(v string) {
	o.Customproperty20 = &v
}

// GetCustomproperty21 returns the Customproperty21 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty21() string {
	if o == nil || IsNil(o.Customproperty21) {
		var ret string
		return ret
	}
	return *o.Customproperty21
}

// GetCustomproperty21Ok returns a tuple with the Customproperty21 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty21Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty21) {
		return nil, false
	}
	return o.Customproperty21, true
}

// HasCustomproperty21 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty21() bool {
	if o != nil && !IsNil(o.Customproperty21) {
		return true
	}

	return false
}

// SetCustomproperty21 gets a reference to the given string and assigns it to the Customproperty21 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty21(v string) {
	o.Customproperty21 = &v
}

// GetCustomproperty22 returns the Customproperty22 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty22() string {
	if o == nil || IsNil(o.Customproperty22) {
		var ret string
		return ret
	}
	return *o.Customproperty22
}

// GetCustomproperty22Ok returns a tuple with the Customproperty22 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty22Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty22) {
		return nil, false
	}
	return o.Customproperty22, true
}

// HasCustomproperty22 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty22() bool {
	if o != nil && !IsNil(o.Customproperty22) {
		return true
	}

	return false
}

// SetCustomproperty22 gets a reference to the given string and assigns it to the Customproperty22 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty22(v string) {
	o.Customproperty22 = &v
}

// GetCustomproperty23 returns the Customproperty23 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty23() string {
	if o == nil || IsNil(o.Customproperty23) {
		var ret string
		return ret
	}
	return *o.Customproperty23
}

// GetCustomproperty23Ok returns a tuple with the Customproperty23 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty23Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty23) {
		return nil, false
	}
	return o.Customproperty23, true
}

// HasCustomproperty23 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty23() bool {
	if o != nil && !IsNil(o.Customproperty23) {
		return true
	}

	return false
}

// SetCustomproperty23 gets a reference to the given string and assigns it to the Customproperty23 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty23(v string) {
	o.Customproperty23 = &v
}

// GetCustomproperty24 returns the Customproperty24 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty24() string {
	if o == nil || IsNil(o.Customproperty24) {
		var ret string
		return ret
	}
	return *o.Customproperty24
}

// GetCustomproperty24Ok returns a tuple with the Customproperty24 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty24Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty24) {
		return nil, false
	}
	return o.Customproperty24, true
}

// HasCustomproperty24 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty24() bool {
	if o != nil && !IsNil(o.Customproperty24) {
		return true
	}

	return false
}

// SetCustomproperty24 gets a reference to the given string and assigns it to the Customproperty24 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty24(v string) {
	o.Customproperty24 = &v
}

// GetCustomproperty25 returns the Customproperty25 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty25() string {
	if o == nil || IsNil(o.Customproperty25) {
		var ret string
		return ret
	}
	return *o.Customproperty25
}

// GetCustomproperty25Ok returns a tuple with the Customproperty25 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty25Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty25) {
		return nil, false
	}
	return o.Customproperty25, true
}

// HasCustomproperty25 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty25() bool {
	if o != nil && !IsNil(o.Customproperty25) {
		return true
	}

	return false
}

// SetCustomproperty25 gets a reference to the given string and assigns it to the Customproperty25 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty25(v string) {
	o.Customproperty25 = &v
}

// GetCustomproperty26 returns the Customproperty26 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty26() string {
	if o == nil || IsNil(o.Customproperty26) {
		var ret string
		return ret
	}
	return *o.Customproperty26
}

// GetCustomproperty26Ok returns a tuple with the Customproperty26 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty26Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty26) {
		return nil, false
	}
	return o.Customproperty26, true
}

// HasCustomproperty26 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty26() bool {
	if o != nil && !IsNil(o.Customproperty26) {
		return true
	}

	return false
}

// SetCustomproperty26 gets a reference to the given string and assigns it to the Customproperty26 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty26(v string) {
	o.Customproperty26 = &v
}

// GetCustomproperty27 returns the Customproperty27 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty27() string {
	if o == nil || IsNil(o.Customproperty27) {
		var ret string
		return ret
	}
	return *o.Customproperty27
}

// GetCustomproperty27Ok returns a tuple with the Customproperty27 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty27Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty27) {
		return nil, false
	}
	return o.Customproperty27, true
}

// HasCustomproperty27 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty27() bool {
	if o != nil && !IsNil(o.Customproperty27) {
		return true
	}

	return false
}

// SetCustomproperty27 gets a reference to the given string and assigns it to the Customproperty27 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty27(v string) {
	o.Customproperty27 = &v
}

// GetCustomproperty28 returns the Customproperty28 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty28() string {
	if o == nil || IsNil(o.Customproperty28) {
		var ret string
		return ret
	}
	return *o.Customproperty28
}

// GetCustomproperty28Ok returns a tuple with the Customproperty28 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty28Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty28) {
		return nil, false
	}
	return o.Customproperty28, true
}

// HasCustomproperty28 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty28() bool {
	if o != nil && !IsNil(o.Customproperty28) {
		return true
	}

	return false
}

// SetCustomproperty28 gets a reference to the given string and assigns it to the Customproperty28 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty28(v string) {
	o.Customproperty28 = &v
}

// GetCustomproperty29 returns the Customproperty29 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty29() string {
	if o == nil || IsNil(o.Customproperty29) {
		var ret string
		return ret
	}
	return *o.Customproperty29
}

// GetCustomproperty29Ok returns a tuple with the Customproperty29 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty29Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty29) {
		return nil, false
	}
	return o.Customproperty29, true
}

// HasCustomproperty29 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty29() bool {
	if o != nil && !IsNil(o.Customproperty29) {
		return true
	}

	return false
}

// SetCustomproperty29 gets a reference to the given string and assigns it to the Customproperty29 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty29(v string) {
	o.Customproperty29 = &v
}

// GetCustomproperty30 returns the Customproperty30 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty30() string {
	if o == nil || IsNil(o.Customproperty30) {
		var ret string
		return ret
	}
	return *o.Customproperty30
}

// GetCustomproperty30Ok returns a tuple with the Customproperty30 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty30Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty30) {
		return nil, false
	}
	return o.Customproperty30, true
}

// HasCustomproperty30 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty30() bool {
	if o != nil && !IsNil(o.Customproperty30) {
		return true
	}

	return false
}

// SetCustomproperty30 gets a reference to the given string and assigns it to the Customproperty30 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty30(v string) {
	o.Customproperty30 = &v
}

// GetCustomproperty31 returns the Customproperty31 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty31() string {
	if o == nil || IsNil(o.Customproperty31) {
		var ret string
		return ret
	}
	return *o.Customproperty31
}

// GetCustomproperty31Ok returns a tuple with the Customproperty31 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty31Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty31) {
		return nil, false
	}
	return o.Customproperty31, true
}

// HasCustomproperty31 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty31() bool {
	if o != nil && !IsNil(o.Customproperty31) {
		return true
	}

	return false
}

// SetCustomproperty31 gets a reference to the given string and assigns it to the Customproperty31 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty31(v string) {
	o.Customproperty31 = &v
}

// GetCustomproperty32 returns the Customproperty32 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty32() string {
	if o == nil || IsNil(o.Customproperty32) {
		var ret string
		return ret
	}
	return *o.Customproperty32
}

// GetCustomproperty32Ok returns a tuple with the Customproperty32 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty32Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty32) {
		return nil, false
	}
	return o.Customproperty32, true
}

// HasCustomproperty32 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty32() bool {
	if o != nil && !IsNil(o.Customproperty32) {
		return true
	}

	return false
}

// SetCustomproperty32 gets a reference to the given string and assigns it to the Customproperty32 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty32(v string) {
	o.Customproperty32 = &v
}

// GetCustomproperty33 returns the Customproperty33 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty33() string {
	if o == nil || IsNil(o.Customproperty33) {
		var ret string
		return ret
	}
	return *o.Customproperty33
}

// GetCustomproperty33Ok returns a tuple with the Customproperty33 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty33Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty33) {
		return nil, false
	}
	return o.Customproperty33, true
}

// HasCustomproperty33 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty33() bool {
	if o != nil && !IsNil(o.Customproperty33) {
		return true
	}

	return false
}

// SetCustomproperty33 gets a reference to the given string and assigns it to the Customproperty33 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty33(v string) {
	o.Customproperty33 = &v
}

// GetCustomproperty34 returns the Customproperty34 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty34() string {
	if o == nil || IsNil(o.Customproperty34) {
		var ret string
		return ret
	}
	return *o.Customproperty34
}

// GetCustomproperty34Ok returns a tuple with the Customproperty34 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty34Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty34) {
		return nil, false
	}
	return o.Customproperty34, true
}

// HasCustomproperty34 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty34() bool {
	if o != nil && !IsNil(o.Customproperty34) {
		return true
	}

	return false
}

// SetCustomproperty34 gets a reference to the given string and assigns it to the Customproperty34 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty34(v string) {
	o.Customproperty34 = &v
}

// GetCustomproperty35 returns the Customproperty35 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty35() string {
	if o == nil || IsNil(o.Customproperty35) {
		var ret string
		return ret
	}
	return *o.Customproperty35
}

// GetCustomproperty35Ok returns a tuple with the Customproperty35 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty35Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty35) {
		return nil, false
	}
	return o.Customproperty35, true
}

// HasCustomproperty35 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty35() bool {
	if o != nil && !IsNil(o.Customproperty35) {
		return true
	}

	return false
}

// SetCustomproperty35 gets a reference to the given string and assigns it to the Customproperty35 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty35(v string) {
	o.Customproperty35 = &v
}

// GetCustomproperty36 returns the Customproperty36 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty36() string {
	if o == nil || IsNil(o.Customproperty36) {
		var ret string
		return ret
	}
	return *o.Customproperty36
}

// GetCustomproperty36Ok returns a tuple with the Customproperty36 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty36Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty36) {
		return nil, false
	}
	return o.Customproperty36, true
}

// HasCustomproperty36 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty36() bool {
	if o != nil && !IsNil(o.Customproperty36) {
		return true
	}

	return false
}

// SetCustomproperty36 gets a reference to the given string and assigns it to the Customproperty36 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty36(v string) {
	o.Customproperty36 = &v
}

// GetCustomproperty37 returns the Customproperty37 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty37() string {
	if o == nil || IsNil(o.Customproperty37) {
		var ret string
		return ret
	}
	return *o.Customproperty37
}

// GetCustomproperty37Ok returns a tuple with the Customproperty37 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty37Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty37) {
		return nil, false
	}
	return o.Customproperty37, true
}

// HasCustomproperty37 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty37() bool {
	if o != nil && !IsNil(o.Customproperty37) {
		return true
	}

	return false
}

// SetCustomproperty37 gets a reference to the given string and assigns it to the Customproperty37 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty37(v string) {
	o.Customproperty37 = &v
}

// GetCustomproperty38 returns the Customproperty38 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty38() string {
	if o == nil || IsNil(o.Customproperty38) {
		var ret string
		return ret
	}
	return *o.Customproperty38
}

// GetCustomproperty38Ok returns a tuple with the Customproperty38 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty38Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty38) {
		return nil, false
	}
	return o.Customproperty38, true
}

// HasCustomproperty38 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty38() bool {
	if o != nil && !IsNil(o.Customproperty38) {
		return true
	}

	return false
}

// SetCustomproperty38 gets a reference to the given string and assigns it to the Customproperty38 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty38(v string) {
	o.Customproperty38 = &v
}

// GetCustomproperty39 returns the Customproperty39 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty39() string {
	if o == nil || IsNil(o.Customproperty39) {
		var ret string
		return ret
	}
	return *o.Customproperty39
}

// GetCustomproperty39Ok returns a tuple with the Customproperty39 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty39Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty39) {
		return nil, false
	}
	return o.Customproperty39, true
}

// HasCustomproperty39 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty39() bool {
	if o != nil && !IsNil(o.Customproperty39) {
		return true
	}

	return false
}

// SetCustomproperty39 gets a reference to the given string and assigns it to the Customproperty39 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty39(v string) {
	o.Customproperty39 = &v
}

// GetCustomproperty40 returns the Customproperty40 field value if set, zero value otherwise.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty40() string {
	if o == nil || IsNil(o.Customproperty40) {
		var ret string
		return ret
	}
	return *o.Customproperty40
}

// GetCustomproperty40Ok returns a tuple with the Customproperty40 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementTypeRequest) GetCustomproperty40Ok() (*string, bool) {
	if o == nil || IsNil(o.Customproperty40) {
		return nil, false
	}
	return o.Customproperty40, true
}

// HasCustomproperty40 returns a boolean if a field has been set.
func (o *UpdateEntitlementTypeRequest) HasCustomproperty40() bool {
	if o != nil && !IsNil(o.Customproperty40) {
		return true
	}

	return false
}

// SetCustomproperty40 gets a reference to the given string and assigns it to the Customproperty40 field.
func (o *UpdateEntitlementTypeRequest) SetCustomproperty40(v string) {
	o.Customproperty40 = &v
}

func (o UpdateEntitlementTypeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEntitlementTypeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entitlementname"] = o.Entitlementname
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	toSerialize["endpointname"] = o.Endpointname
	if !IsNil(o.Entitlementdescription) {
		toSerialize["entitlementdescription"] = o.Entitlementdescription
	}
	if !IsNil(o.Workflow) {
		toSerialize["workflow"] = o.Workflow
	}
	if !IsNil(o.EnableEntitlementToRoleSync) {
		toSerialize["enableEntitlementToRoleSync"] = o.EnableEntitlementToRoleSync
	}
	if !IsNil(o.AvailableQueryServiceAccount) {
		toSerialize["availableQueryServiceAccount"] = o.AvailableQueryServiceAccount
	}
	if !IsNil(o.SelectedQueryServiceAccount) {
		toSerialize["selectedQueryServiceAccount"] = o.SelectedQueryServiceAccount
	}
	if !IsNil(o.ArsRequestableEntitlementQuery) {
		toSerialize["arsRequestableEntitlementQuery"] = o.ArsRequestableEntitlementQuery
	}
	if !IsNil(o.ArsSelectedEntitlementQuery) {
		toSerialize["arsSelectedEntitlementQuery"] = o.ArsSelectedEntitlementQuery
	}
	if !IsNil(o.Certifiable) {
		toSerialize["certifiable"] = o.Certifiable
	}
	if !IsNil(o.CreateTaskAction) {
		toSerialize["createTaskAction"] = o.CreateTaskAction
	}
	if !IsNil(o.RequestDatesConfJson) {
		toSerialize["requestDatesConfJson"] = o.RequestDatesConfJson
	}
	if !IsNil(o.StartDateInRevokeRequest) {
		toSerialize["startDateInRevokeRequest"] = o.StartDateInRevokeRequest
	}
	if !IsNil(o.StartEndDateInRequest) {
		toSerialize["startEndDateInRequest"] = o.StartEndDateInRequest
	}
	if !IsNil(o.AllowRemoveAllEntitlementInRequest) {
		toSerialize["allowRemoveAllEntitlementInRequest"] = o.AllowRemoveAllEntitlementInRequest
	}
	if !IsNil(o.Orderindex) {
		toSerialize["orderindex"] = o.Orderindex
	}
	if !IsNil(o.Requiredinrequest) {
		toSerialize["requiredinrequest"] = o.Requiredinrequest
	}
	if !IsNil(o.Requiredinservicerequest) {
		toSerialize["requiredinservicerequest"] = o.Requiredinservicerequest
	}
	if !IsNil(o.Hiearchyrequired) {
		toSerialize["hiearchyrequired"] = o.Hiearchyrequired
	}
	if !IsNil(o.ShowEntTypeOn) {
		toSerialize["showEntTypeOn"] = o.ShowEntTypeOn
	}
	if !IsNil(o.EnableProvisioningPriority) {
		toSerialize["enableProvisioningPriority"] = o.EnableProvisioningPriority
	}
	if !IsNil(o.ExcludeRuleAssgnEntsInRequest) {
		toSerialize["excludeRuleAssgnEntsInRequest"] = o.ExcludeRuleAssgnEntsInRequest
	}
	if !IsNil(o.Recon) {
		toSerialize["recon"] = o.Recon
	}
	if !IsNil(o.Showonchild) {
		toSerialize["showonchild"] = o.Showonchild
	}
	if !IsNil(o.Requestoption) {
		toSerialize["requestoption"] = o.Requestoption
	}
	if !IsNil(o.Customproperty1) {
		toSerialize["customproperty1"] = o.Customproperty1
	}
	if !IsNil(o.Customproperty2) {
		toSerialize["customproperty2"] = o.Customproperty2
	}
	if !IsNil(o.Customproperty3) {
		toSerialize["customproperty3"] = o.Customproperty3
	}
	if !IsNil(o.Customproperty4) {
		toSerialize["customproperty4"] = o.Customproperty4
	}
	if !IsNil(o.Customproperty5) {
		toSerialize["customproperty5"] = o.Customproperty5
	}
	if !IsNil(o.Customproperty6) {
		toSerialize["customproperty6"] = o.Customproperty6
	}
	if !IsNil(o.Customproperty7) {
		toSerialize["customproperty7"] = o.Customproperty7
	}
	if !IsNil(o.Customproperty8) {
		toSerialize["customproperty8"] = o.Customproperty8
	}
	if !IsNil(o.Customproperty9) {
		toSerialize["customproperty9"] = o.Customproperty9
	}
	if !IsNil(o.Customproperty10) {
		toSerialize["customproperty10"] = o.Customproperty10
	}
	if !IsNil(o.Customproperty11) {
		toSerialize["customproperty11"] = o.Customproperty11
	}
	if !IsNil(o.Customproperty12) {
		toSerialize["customproperty12"] = o.Customproperty12
	}
	if !IsNil(o.Customproperty13) {
		toSerialize["customproperty13"] = o.Customproperty13
	}
	if !IsNil(o.Customproperty14) {
		toSerialize["customproperty14"] = o.Customproperty14
	}
	if !IsNil(o.Customproperty15) {
		toSerialize["customproperty15"] = o.Customproperty15
	}
	if !IsNil(o.Customproperty16) {
		toSerialize["customproperty16"] = o.Customproperty16
	}
	if !IsNil(o.Customproperty17) {
		toSerialize["customproperty17"] = o.Customproperty17
	}
	if !IsNil(o.Customproperty18) {
		toSerialize["customproperty18"] = o.Customproperty18
	}
	if !IsNil(o.Customproperty19) {
		toSerialize["customproperty19"] = o.Customproperty19
	}
	if !IsNil(o.Customproperty20) {
		toSerialize["customproperty20"] = o.Customproperty20
	}
	if !IsNil(o.Customproperty21) {
		toSerialize["customproperty21"] = o.Customproperty21
	}
	if !IsNil(o.Customproperty22) {
		toSerialize["customproperty22"] = o.Customproperty22
	}
	if !IsNil(o.Customproperty23) {
		toSerialize["customproperty23"] = o.Customproperty23
	}
	if !IsNil(o.Customproperty24) {
		toSerialize["customproperty24"] = o.Customproperty24
	}
	if !IsNil(o.Customproperty25) {
		toSerialize["customproperty25"] = o.Customproperty25
	}
	if !IsNil(o.Customproperty26) {
		toSerialize["customproperty26"] = o.Customproperty26
	}
	if !IsNil(o.Customproperty27) {
		toSerialize["customproperty27"] = o.Customproperty27
	}
	if !IsNil(o.Customproperty28) {
		toSerialize["customproperty28"] = o.Customproperty28
	}
	if !IsNil(o.Customproperty29) {
		toSerialize["customproperty29"] = o.Customproperty29
	}
	if !IsNil(o.Customproperty30) {
		toSerialize["customproperty30"] = o.Customproperty30
	}
	if !IsNil(o.Customproperty31) {
		toSerialize["customproperty31"] = o.Customproperty31
	}
	if !IsNil(o.Customproperty32) {
		toSerialize["customproperty32"] = o.Customproperty32
	}
	if !IsNil(o.Customproperty33) {
		toSerialize["customproperty33"] = o.Customproperty33
	}
	if !IsNil(o.Customproperty34) {
		toSerialize["customproperty34"] = o.Customproperty34
	}
	if !IsNil(o.Customproperty35) {
		toSerialize["customproperty35"] = o.Customproperty35
	}
	if !IsNil(o.Customproperty36) {
		toSerialize["customproperty36"] = o.Customproperty36
	}
	if !IsNil(o.Customproperty37) {
		toSerialize["customproperty37"] = o.Customproperty37
	}
	if !IsNil(o.Customproperty38) {
		toSerialize["customproperty38"] = o.Customproperty38
	}
	if !IsNil(o.Customproperty39) {
		toSerialize["customproperty39"] = o.Customproperty39
	}
	if !IsNil(o.Customproperty40) {
		toSerialize["customproperty40"] = o.Customproperty40
	}
	return toSerialize, nil
}

func (o *UpdateEntitlementTypeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entitlementname",
		"endpointname",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateEntitlementTypeRequest := _UpdateEntitlementTypeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateEntitlementTypeRequest)

	if err != nil {
		return err
	}

	*o = UpdateEntitlementTypeRequest(varUpdateEntitlementTypeRequest)

	return err
}

type NullableUpdateEntitlementTypeRequest struct {
	value *UpdateEntitlementTypeRequest
	isSet bool
}

func (v NullableUpdateEntitlementTypeRequest) Get() *UpdateEntitlementTypeRequest {
	return v.value
}

func (v *NullableUpdateEntitlementTypeRequest) Set(val *UpdateEntitlementTypeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEntitlementTypeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEntitlementTypeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEntitlementTypeRequest(val *UpdateEntitlementTypeRequest) *NullableUpdateEntitlementTypeRequest {
	return &NullableUpdateEntitlementTypeRequest{value: val, isSet: true}
}

func (v NullableUpdateEntitlementTypeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEntitlementTypeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
