/*
Entitlement Management API

API for managing entitlements in Saviynt/SSM. - **Create Entitlement**: Creates a new entitlement. - **Update Entitlement**: Updates an existing entitlement. - **Get Entitlement List**: Returns a list of entitlement based on search criteria. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entitlements

import (
	"encoding/json"
)

// checks if the GetEntitlementResponseEntitlementdetailsInnerAccountsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEntitlementResponseEntitlementdetailsInnerAccountsInner{}

// GetEntitlementResponseEntitlementdetailsInnerAccountsInner struct for GetEntitlementResponseEntitlementdetailsInnerAccountsInner
type GetEntitlementResponseEntitlementdetailsInnerAccountsInner struct {
	// End date of the account association.
	Enddate *string `json:"enddate,omitempty"`
	// Name of the associated account.
	Accountname *string `json:"accountname,omitempty"`
	// Update date of the account association.
	Updatedate *string `json:"updatedate,omitempty"`
	// Start date of the account association.
	Startdate *string `json:"startdate,omitempty"`
}

// NewGetEntitlementResponseEntitlementdetailsInnerAccountsInner instantiates a new GetEntitlementResponseEntitlementdetailsInnerAccountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEntitlementResponseEntitlementdetailsInnerAccountsInner() *GetEntitlementResponseEntitlementdetailsInnerAccountsInner {
	this := GetEntitlementResponseEntitlementdetailsInnerAccountsInner{}
	return &this
}

// NewGetEntitlementResponseEntitlementdetailsInnerAccountsInnerWithDefaults instantiates a new GetEntitlementResponseEntitlementdetailsInnerAccountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEntitlementResponseEntitlementdetailsInnerAccountsInnerWithDefaults() *GetEntitlementResponseEntitlementdetailsInnerAccountsInner {
	this := GetEntitlementResponseEntitlementdetailsInnerAccountsInner{}
	return &this
}

// GetEnddate returns the Enddate field value if set, zero value otherwise.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) GetEnddate() string {
	if o == nil || IsNil(o.Enddate) {
		var ret string
		return ret
	}
	return *o.Enddate
}

// GetEnddateOk returns a tuple with the Enddate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) GetEnddateOk() (*string, bool) {
	if o == nil || IsNil(o.Enddate) {
		return nil, false
	}
	return o.Enddate, true
}

// HasEnddate returns a boolean if a field has been set.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) HasEnddate() bool {
	if o != nil && !IsNil(o.Enddate) {
		return true
	}

	return false
}

// SetEnddate gets a reference to the given string and assigns it to the Enddate field.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) SetEnddate(v string) {
	o.Enddate = &v
}

// GetAccountname returns the Accountname field value if set, zero value otherwise.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) GetAccountname() string {
	if o == nil || IsNil(o.Accountname) {
		var ret string
		return ret
	}
	return *o.Accountname
}

// GetAccountnameOk returns a tuple with the Accountname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) GetAccountnameOk() (*string, bool) {
	if o == nil || IsNil(o.Accountname) {
		return nil, false
	}
	return o.Accountname, true
}

// HasAccountname returns a boolean if a field has been set.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) HasAccountname() bool {
	if o != nil && !IsNil(o.Accountname) {
		return true
	}

	return false
}

// SetAccountname gets a reference to the given string and assigns it to the Accountname field.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) SetAccountname(v string) {
	o.Accountname = &v
}

// GetUpdatedate returns the Updatedate field value if set, zero value otherwise.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) GetUpdatedate() string {
	if o == nil || IsNil(o.Updatedate) {
		var ret string
		return ret
	}
	return *o.Updatedate
}

// GetUpdatedateOk returns a tuple with the Updatedate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) GetUpdatedateOk() (*string, bool) {
	if o == nil || IsNil(o.Updatedate) {
		return nil, false
	}
	return o.Updatedate, true
}

// HasUpdatedate returns a boolean if a field has been set.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) HasUpdatedate() bool {
	if o != nil && !IsNil(o.Updatedate) {
		return true
	}

	return false
}

// SetUpdatedate gets a reference to the given string and assigns it to the Updatedate field.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) SetUpdatedate(v string) {
	o.Updatedate = &v
}

// GetStartdate returns the Startdate field value if set, zero value otherwise.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) GetStartdate() string {
	if o == nil || IsNil(o.Startdate) {
		var ret string
		return ret
	}
	return *o.Startdate
}

// GetStartdateOk returns a tuple with the Startdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) GetStartdateOk() (*string, bool) {
	if o == nil || IsNil(o.Startdate) {
		return nil, false
	}
	return o.Startdate, true
}

// HasStartdate returns a boolean if a field has been set.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) HasStartdate() bool {
	if o != nil && !IsNil(o.Startdate) {
		return true
	}

	return false
}

// SetStartdate gets a reference to the given string and assigns it to the Startdate field.
func (o *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) SetStartdate(v string) {
	o.Startdate = &v
}

func (o GetEntitlementResponseEntitlementdetailsInnerAccountsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEntitlementResponseEntitlementdetailsInnerAccountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enddate) {
		toSerialize["enddate"] = o.Enddate
	}
	if !IsNil(o.Accountname) {
		toSerialize["accountname"] = o.Accountname
	}
	if !IsNil(o.Updatedate) {
		toSerialize["updatedate"] = o.Updatedate
	}
	if !IsNil(o.Startdate) {
		toSerialize["startdate"] = o.Startdate
	}
	return toSerialize, nil
}

type NullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner struct {
	value *GetEntitlementResponseEntitlementdetailsInnerAccountsInner
	isSet bool
}

func (v NullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner) Get() *GetEntitlementResponseEntitlementdetailsInnerAccountsInner {
	return v.value
}

func (v *NullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner) Set(val *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner(val *GetEntitlementResponseEntitlementdetailsInnerAccountsInner) *NullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner {
	return &NullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner{value: val, isSet: true}
}

func (v NullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEntitlementResponseEntitlementdetailsInnerAccountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


