resource "saviynt_security_system_resource" "example1" {
  systemname                            = "SYSTEM_NAME"
  display_name                          = "DISPLAY_NAME"
  hostname                              = "HOST_NAME"
  port                                  = "PORT"
  access_add_workflow                   = "ADD_ACCESS_WORKFLOW"
  access_remove_workflow                = "ACCESS_REMOVE_WORKFLOW"
  add_service_account_workflow          = "ADD_SERVICE_ACCOUNT_WORKFLOW"
  remove_service_account_workflow       = "REMOVE_SERVICE_ACCOUNT_WORKFLOW"
  firefighterid_workflow                = "FIREFIGHTER_ID_WORKFLOW"
  firefighterid_request_access_workflow = "FIREFIGHTER_REQUEST_ACCESS_WORKFLOW"
  policy_rule                           = "POLICY_RULE"
  policy_rule_service_account           = "POLICY_RULE_SERVICE_ACCOUNT"
  recon_application                     = "RECON_APPLICATION"
  instant_provision                     = "INSTANT_PROVISION"
  provisioning_tries                    = "PROVISIONING_TRIES"
  connection_parameters                 = "CONNECTION_PARAMS"
  automated_provisioning                = "AUTOMATED_PROVISIONING"
  use_open_connector                    = "USE_OPEN_CONNECTOR_NAME"
  provisioning_comments                 = "PROVISIONING_COMMENTS"
  proposed_account_owners_workflow      = "PROPOSED_ACCOUNT_WORKFLOW"
  connectionname                        = "CONNECTION_NAME"
  provisioning_connection               = "PROVISIONING_CONNECTION"
  service_desk_connection               = "SERVICE_DEST_CONNECTION"
  inherent_sod_report_fields            = "INHERENT_SOD_REPORT_FIELDS"
  external_risk_connection_json         = "EXTERNAL_RISK_CONNECTION_JSON"
}
