/*
Saviynt API

API for managing roles in Saviynt.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package roles

import (
	"encoding/json"
)

// checks if the AddOrRemoveRoleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddOrRemoveRoleResponse{}

// AddOrRemoveRoleResponse struct for AddOrRemoveRoleResponse
type AddOrRemoveRoleResponse struct {
	Message   *string `json:"message,omitempty"`
	ErrorCode *string `json:"errorCode,omitempty"`
}

// NewAddOrRemoveRoleResponse instantiates a new AddOrRemoveRoleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddOrRemoveRoleResponse() *AddOrRemoveRoleResponse {
	this := AddOrRemoveRoleResponse{}
	return &this
}

// NewAddOrRemoveRoleResponseWithDefaults instantiates a new AddOrRemoveRoleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddOrRemoveRoleResponseWithDefaults() *AddOrRemoveRoleResponse {
	this := AddOrRemoveRoleResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AddOrRemoveRoleResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddOrRemoveRoleResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AddOrRemoveRoleResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AddOrRemoveRoleResponse) SetMessage(v string) {
	o.Message = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *AddOrRemoveRoleResponse) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddOrRemoveRoleResponse) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *AddOrRemoveRoleResponse) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *AddOrRemoveRoleResponse) SetErrorCode(v string) {
	o.ErrorCode = &v
}

func (o AddOrRemoveRoleResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddOrRemoveRoleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	return toSerialize, nil
}

type NullableAddOrRemoveRoleResponse struct {
	value *AddOrRemoveRoleResponse
	isSet bool
}

func (v NullableAddOrRemoveRoleResponse) Get() *AddOrRemoveRoleResponse {
	return v.value
}

func (v *NullableAddOrRemoveRoleResponse) Set(val *AddOrRemoveRoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddOrRemoveRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddOrRemoveRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddOrRemoveRoleResponse(val *AddOrRemoveRoleResponse) *NullableAddOrRemoveRoleResponse {
	return &NullableAddOrRemoveRoleResponse{value: val, isSet: true}
}

func (v NullableAddOrRemoveRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddOrRemoveRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
