resource "saviynt_sap_connection_resource" "ss" {
  connection_type = "SAP"
  connection_name = "namefortheconnection"
  message_server   = "sapms01"
  jco_ashost       = "sap-app-server.local"
  jco_sysnr        = "00"
  jco_client       = "100"
  jco_user         = "SAPUSER"
  password         = "MySecret123!"
  jco_lang         = "EN"
  jco_r3name       = "PRD"
  jco_mshost       = "sap-message-server.local"
  jco_msserv       = "3600"
  jco_group        = "GROUP1"
  snc              = "false"
  jco_snc_mode     = "0"
  jco_snc_partnername = ""
  jco_snc_myname   = ""
  jco_snc_library  = ""
  jco_snc_qop      = ""
  tables           = "AGR_USERS, USR04"
  system_name      = "SAP_PROD"
  terminated_user_group = "SAP_TERMINATED"
  terminated_user_role_action = "REMOVE"
  create_account_json = "{\"user\":\"template\"}"
  prov_jco_ashost  = "prov-sap-app-server.local"
  prov_jco_sysnr   = "01"
  prov_jco_client  = "200"
  prov_jco_user    = "SAPPROVUSER"
  prov_password    = "ProvSecret@123"
  prov_jco_lang    = "EN"
  prov_jco_r3name  = "QAS"
  prov_jco_mshost  = "prov-message-server.local"
  prov_jco_msserv  = "3900"
  prov_jco_group   = "PROV_GROUP"
  prov_cua_enabled = "false"
  prov_cua_snc     = "false"
  reset_pwd_for_newaccount = "true"
  enforce_password_change  = "true"
  password_min_length      = "8"
  password_max_length      = "16"
  password_no_of_caps_alpha = "2"
  password_no_of_digits     = "2"
  password_no_of_spl_chars  = "1"
  hanareftablejson = "{\"hanaTable\":\"Z_TABLE\"}"
  enable_account_json = "{\"ENABLE\":\"yes\"}"
  update_account_json = "{\"UPDATE\":\"standard\"}"
  user_import_json    = "{\"IMPORT_TYPE\":\"full\"}"
  status_threshold_config = <<EOT
  {
    "statusAndThresholdConfig": {
      "accountStatusAttribute": "userAccountControl",
      "activeStatusValue": ["512", "544"],
      "suspendedStatusValue": ["546"],
      "disableStatusValue": ["514"],
      "thresholdKey": "lockoutThreshold",
      "lockoutValue": "3"
    }
  }
  EOT
  set_cua_system = "SAP_CUA"
  fire_fighter_id_grant_access_json = "{\"GRANT\":\"yes\"}"
  fire_fighter_id_revoke_access_json = "{\"REVOKE\":\"yes\"}"
  modify_user_data_json = "{\"MODIFY\":\"enabled\"}"
  external_sod_eval_json = "{\"EVAL\":\"true\"}"
  external_sod_eval_json_detail = "{\"DETAIL\":\"on\"}"
  logs_table_filter = "USRLOG, STAD"
  pam_config = "{\"enabled\": true, \"vault\": \"hashicorp\"}"
  saptable_filter_lang = "EN"
  alternate_output_parameter_et_data = "custom_param"
  audit_log_json = "{\"LOG_LEVEL\":\"FULL\"}"
  ecc_or_s4hana = "S4HANA"
  data_import_filter = "{\"filter\":\"import_filter_condition\"}"
  config_json = "{\"connectionTimeout\":30,\"retryCount\":3}"
}